library(Seurat)
library(patchwork)
library(tidyverse)
library(cowplot)
library(data.table)
library(Matrix)
library(dplyr)
library(readxl)
library(wrapr)

setwd("~/Library/CloudStorage/GoogleDrive-caio.mussatto@unesp.br/Meu Drive/Projeto_de_Pesquisa /DATA")

# Lendo os arquivos

linhagens <- readRDS('linhagens.rds')
lista_CIFS <- read.table('CIFS_filtrada.txt')

write.csv(lista_CIFS, 'CIFS_filtrada.csv')

#linhagens_sample <- as_tibble(linhagens$sample)

#linhagens_sample <- distinct(linhagens_sample)

#write_csv(linhagens_sample, 'linhagens_sample.csv')

linhagens_sample <- read_csv('linhagens_sample.csv')


# THYROID

DotPlot <- DotPlot(linhagens, features = lista_CIFS$V1[1:6], idents = linhagens_sample$value[1:4])
DotPlot1 <- DotPlot(linhagens, features = lista_CIFS$V1[6:11], idents = linhagens_sample$value[1:4])
DotPlot2 <- DotPlot(linhagens, features = lista_CIFS$V1[12:17], idents = linhagens_sample$value[1:4])
DotPlot3 <- DotPlot(linhagens, features = lista_CIFS$V1[18:23], idents = linhagens_sample$value[1:4])
DotPlot4 <- DotPlot(linhagens, features = lista_CIFS$V1[24:29], idents = linhagens_sample$value[1:4])
DotPlot5 <- DotPlot(linhagens, features = lista_CIFS$V1[30:35], idents = linhagens_sample$value[1:4])
DotPlot6 <- DotPlot(linhagens, features = lista_CIFS$V1[36:41], idents = linhagens_sample$value[1:4])
DotPlot7 <- DotPlot(linhagens, features = lista_CIFS$V1[42:47], idents = linhagens_sample$value[1:4])
DotPlot8 <- DotPlot(linhagens, features = lista_CIFS$V1[48:53], idents = linhagens_sample$value[1:4])
DotPlot9 <- DotPlot(linhagens, features = lista_CIFS$V1[54:59], idents = linhagens_sample$value[1:4])
DotPlot10 <- DotPlot(linhagens, features = lista_CIFS$V1[60:65], idents = linhagens_sample$value[1:4])
DotPlot11 <- DotPlot(linhagens, features = lista_CIFS$V1[66:71], idents = linhagens_sample$value[1:4])
DotPlot12 <- DotPlot(linhagens, features = lista_CIFS$V1[72:77], idents = linhagens_sample$value[1:4])
DotPlot13 <- DotPlot(linhagens, features = lista_CIFS$V1[78:83], idents = linhagens_sample$value[1:4])
DotPlot14 <- DotPlot(linhagens, features = lista_CIFS$V1[84:89], idents = linhagens_sample$value[1:4])
DotPlot15 <- DotPlot(linhagens, features = lista_CIFS$V1[90:95], idents = linhagens_sample$value[1:4])
DotPlot16<- DotPlot(linhagens, features = lista_CIFS$V1[96:102], idents = linhagens_sample$value[1:4])

ggsave('Imagens/DotPlot.tiff', plot = DotPlot, width = 10, height = 15)
ggsave('Imagens/DotPlot1.tiff', plot = DotPlot1, width = 10, height = 15)
ggsave('Imagens/DotPlot2.tiff', plot = DotPlot2, width = 10, height = 15)
ggsave('Imagens/DotPlot3.tiff', plot = DotPlot3, width = 10, height = 15)
ggsave('Imagens/DotPlot4.tiff', plot = DotPlot4, width = 10, height = 15)
ggsave('Imagens/DotPlot5.tiff', plot = DotPlot5, width = 10, height = 15)
ggsave('Imagens/DotPlot6.tiff', plot = DotPlot6, width = 10, height = 15)
ggsave('Imagens/DotPlot7.tiff', plot = DotPlot7, width = 10, height = 15)
ggsave('Imagens/DotPlot8.tiff', plot = DotPlot8, width = 10, height = 15)
ggsave('Imagens/DotPlot9.tiff', plot = DotPlot9, width = 10, height = 15)
ggsave('Imagens/DotPlot10.tiff', plot = DotPlot10, width = 10, height = 15)
ggsave('Imagens/DotPlot11.tiff', plot = DotPlot11, width = 10, height = 15)
ggsave('Imagens/DotPlot12.tiff', plot = DotPlot12, width = 10, height = 15)
ggsave('Imagens/DotPlot13.tiff', plot = DotPlot13, width = 10, height = 15)
ggsave('Imagens/DotPlot14.tiff', plot = DotPlot14, width = 10, height = 15)
ggsave('Imagens/DotPlot15.tiff', plot = DotPlot15, width = 10, height = 15)
ggsave('Imagens/DotPlot16.tiff', plot = DotPlot16, width = 10, height = 15)

# ENDOMETRIUM

DotPlot <- DotPlot(linhagens, features = lista_CIFS$V1[1:6], idents = linhagens_sample$value[5:9])
DotPlot1 <- DotPlot(linhagens, features = lista_CIFS$V1[6:11], idents = linhagens_sample$value[5:9])
DotPlot2 <- DotPlot(linhagens, features = lista_CIFS$V1[12:17], idents = linhagens_sample$value[5:9])
DotPlot3 <- DotPlot(linhagens, features = lista_CIFS$V1[18:23], idents = linhagens_sample$value[5:9])
DotPlot4 <- DotPlot(linhagens, features = lista_CIFS$V1[24:29], idents = linhagens_sample$value[5:9])
DotPlot5 <- DotPlot(linhagens, features = lista_CIFS$V1[30:35], idents = linhagens_sample$value[5:9])
DotPlot6 <- DotPlot(linhagens, features = lista_CIFS$V1[36:41], idents = linhagens_sample$value[5:9])
DotPlot7 <- DotPlot(linhagens, features = lista_CIFS$V1[42:47], idents = linhagens_sample$value[5:9])
DotPlot8 <- DotPlot(linhagens, features = lista_CIFS$V1[48:53], idents = linhagens_sample$value[5:9])
DotPlot9 <- DotPlot(linhagens, features = lista_CIFS$V1[54:59], idents = linhagens_sample$value[5:9])
DotPlot10 <- DotPlot(linhagens, features = lista_CIFS$V1[60:65], idents = linhagens_sample$value[5:9])
DotPlot11 <- DotPlot(linhagens, features = lista_CIFS$V1[66:71], idents = linhagens_sample$value[5:9])
DotPlot12 <- DotPlot(linhagens, features = lista_CIFS$V1[72:77], idents = linhagens_sample$value[5:9])
DotPlot13 <- DotPlot(linhagens, features = lista_CIFS$V1[78:83], idents = linhagens_sample$value[5:9])
DotPlot14 <- DotPlot(linhagens, features = lista_CIFS$V1[84:89], idents = linhagens_sample$value[5:9])
DotPlot15 <- DotPlot(linhagens, features = lista_CIFS$V1[90:95], idents = linhagens_sample$value[5:9])
DotPlot16<- DotPlot(linhagens, features = lista_CIFS$V1[96:102], idents = linhagens_sample$value[5:9])

ggsave('Imagens/DotPlot.tiff', plot = DotPlot, width = 10, height = 15)
ggsave('Imagens/DotPlot1.tiff', plot = DotPlot1, width = 10, height = 15)
ggsave('Imagens/DotPlot2.tiff', plot = DotPlot2, width = 10, height = 15)
ggsave('Imagens/DotPlot3.tiff', plot = DotPlot3, width = 10, height = 15)
ggsave('Imagens/DotPlot4.tiff', plot = DotPlot4, width = 10, height = 15)
ggsave('Imagens/DotPlot5.tiff', plot = DotPlot5, width = 10, height = 15)
ggsave('Imagens/DotPlot6.tiff', plot = DotPlot6, width = 10, height = 15)
ggsave('Imagens/DotPlot7.tiff', plot = DotPlot7, width = 10, height = 15)
ggsave('Imagens/DotPlot8.tiff', plot = DotPlot8, width = 10, height = 15)
ggsave('Imagens/DotPlot9.tiff', plot = DotPlot9, width = 10, height = 15)
ggsave('Imagens/DotPlot10.tiff', plot = DotPlot10, width = 10, height = 15)
ggsave('Imagens/DotPlot11.tiff', plot = DotPlot11, width = 10, height = 15)
ggsave('Imagens/DotPlot12.tiff', plot = DotPlot12, width = 10, height = 15)
ggsave('Imagens/DotPlot13.tiff', plot = DotPlot13, width = 10, height = 15)
ggsave('Imagens/DotPlot14.tiff', plot = DotPlot14, width = 10, height = 15)
ggsave('Imagens/DotPlot15.tiff', plot = DotPlot15, width = 10, height = 15)
ggsave('Imagens/DotPlot16.tiff', plot = DotPlot16, width = 10, height = 15)

# SKIN

DotPlot <- DotPlot(linhagens, features = lista_CIFS$V1[1:6], idents = linhagens_sample$value[10:14])
DotPlot1 <- DotPlot(linhagens, features = lista_CIFS$V1[6:11], idents = linhagens_sample$value[10:14])
DotPlot2 <- DotPlot(linhagens, features = lista_CIFS$V1[12:17], idents = linhagens_sample$value[10:14])
DotPlot3 <- DotPlot(linhagens, features = lista_CIFS$V1[18:23], idents = linhagens_sample$value[10:14])
DotPlot4 <- DotPlot(linhagens, features = lista_CIFS$V1[24:29], idents = linhagens_sample$value[10:14])
DotPlot5 <- DotPlot(linhagens, features = lista_CIFS$V1[30:35], idents = linhagens_sample$value[10:14])
DotPlot6 <- DotPlot(linhagens, features = lista_CIFS$V1[36:41], idents = linhagens_sample$value[10:14])
DotPlot7 <- DotPlot(linhagens, features = lista_CIFS$V1[42:47], idents = linhagens_sample$value[10:14])
DotPlot8 <- DotPlot(linhagens, features = lista_CIFS$V1[48:53], idents = linhagens_sample$value[10:14])
DotPlot9 <- DotPlot(linhagens, features = lista_CIFS$V1[54:59], idents = linhagens_sample$value[10:14])
DotPlot10 <- DotPlot(linhagens, features = lista_CIFS$V1[60:65], idents = linhagens_sample$value[10:14])
DotPlot11 <- DotPlot(linhagens, features = lista_CIFS$V1[66:71], idents = linhagens_sample$value[10:14])
DotPlot12 <- DotPlot(linhagens, features = lista_CIFS$V1[72:77], idents = linhagens_sample$value[10:14])
DotPlot13 <- DotPlot(linhagens, features = lista_CIFS$V1[78:83], idents = linhagens_sample$value[10:14])
DotPlot14 <- DotPlot(linhagens, features = lista_CIFS$V1[84:89], idents = linhagens_sample$value[10:14])
DotPlot15 <- DotPlot(linhagens, features = lista_CIFS$V1[90:95], idents = linhagens_sample$value[10:14])
DotPlot16<- DotPlot(linhagens, features = lista_CIFS$V1[96:102], idents = linhagens_sample$value[10:14])

ggsave('Imagens/DotPlot.tiff', plot = DotPlot, width = 10, height = 15)
ggsave('Imagens/DotPlot1.tiff', plot = DotPlot1, width = 10, height = 15)
ggsave('Imagens/DotPlot2.tiff', plot = DotPlot2, width = 10, height = 15)
ggsave('Imagens/DotPlot3.tiff', plot = DotPlot3, width = 10, height = 15)
ggsave('Imagens/DotPlot4.tiff', plot = DotPlot4, width = 10, height = 15)
ggsave('Imagens/DotPlot5.tiff', plot = DotPlot5, width = 10, height = 15)
ggsave('Imagens/DotPlot6.tiff', plot = DotPlot6, width = 10, height = 15)
ggsave('Imagens/DotPlot7.tiff', plot = DotPlot7, width = 10, height = 15)
ggsave('Imagens/DotPlot8.tiff', plot = DotPlot8, width = 10, height = 15)
ggsave('Imagens/DotPlot9.tiff', plot = DotPlot9, width = 10, height = 15)
ggsave('Imagens/DotPlot10.tiff', plot = DotPlot10, width = 10, height = 15)
ggsave('Imagens/DotPlot11.tiff', plot = DotPlot11, width = 10, height = 15)
ggsave('Imagens/DotPlot12.tiff', plot = DotPlot12, width = 10, height = 15)
ggsave('Imagens/DotPlot13.tiff', plot = DotPlot13, width = 10, height = 15)
ggsave('Imagens/DotPlot14.tiff', plot = DotPlot14, width = 10, height = 15)
ggsave('Imagens/DotPlot15.tiff', plot = DotPlot15, width = 10, height = 15)
ggsave('Imagens/DotPlot16.tiff', plot = DotPlot16, width = 10, height = 15)

# LIVER

DotPlot <- DotPlot(linhagens, features = lista_CIFS$V1[1:6], idents = linhagens_sample$value[15:19])
DotPlot1 <- DotPlot(linhagens, features = lista_CIFS$V1[6:11], idents = linhagens_sample$value[15:19])
DotPlot2 <- DotPlot(linhagens, features = lista_CIFS$V1[12:17], idents = linhagens_sample$value[15:19])
DotPlot3 <- DotPlot(linhagens, features = lista_CIFS$V1[18:23], idents = linhagens_sample$value[15:19])
DotPlot4 <- DotPlot(linhagens, features = lista_CIFS$V1[24:29], idents = linhagens_sample$value[15:19])
DotPlot5 <- DotPlot(linhagens, features = lista_CIFS$V1[30:35], idents = linhagens_sample$value[15:19])
DotPlot6 <- DotPlot(linhagens, features = lista_CIFS$V1[36:41], idents = linhagens_sample$value[15:19])
DotPlot7 <- DotPlot(linhagens, features = lista_CIFS$V1[42:47], idents = linhagens_sample$value[15:19])
DotPlot8 <- DotPlot(linhagens, features = lista_CIFS$V1[48:53], idents = linhagens_sample$value[15:19])
DotPlot9 <- DotPlot(linhagens, features = lista_CIFS$V1[54:59], idents = linhagens_sample$value[15:19])
DotPlot10 <- DotPlot(linhagens, features = lista_CIFS$V1[60:65], idents = linhagens_sample$value[15:19])
DotPlot11 <- DotPlot(linhagens, features = lista_CIFS$V1[66:71], idents = linhagens_sample$value[15:19])
DotPlot12 <- DotPlot(linhagens, features = lista_CIFS$V1[72:77], idents = linhagens_sample$value[15:19])
DotPlot13 <- DotPlot(linhagens, features = lista_CIFS$V1[78:83], idents = linhagens_sample$value[15:19])
DotPlot14 <- DotPlot(linhagens, features = lista_CIFS$V1[84:89], idents = linhagens_sample$value[15:19])
DotPlot15 <- DotPlot(linhagens, features = lista_CIFS$V1[90:95], idents = linhagens_sample$value[15:19])
DotPlot16<- DotPlot(linhagens, features = lista_CIFS$V1[96:102], idents = linhagens_sample$value[15:19])

ggsave('Imagens/DotPlot.tiff', plot = DotPlot, width = 10, height = 15)
ggsave('Imagens/DotPlot1.tiff', plot = DotPlot1, width = 10, height = 15)
ggsave('Imagens/DotPlot2.tiff', plot = DotPlot2, width = 10, height = 15)
ggsave('Imagens/DotPlot3.tiff', plot = DotPlot3, width = 10, height = 15)
ggsave('Imagens/DotPlot4.tiff', plot = DotPlot4, width = 10, height = 15)
ggsave('Imagens/DotPlot5.tiff', plot = DotPlot5, width = 10, height = 15)
ggsave('Imagens/DotPlot6.tiff', plot = DotPlot6, width = 10, height = 15)
ggsave('Imagens/DotPlot7.tiff', plot = DotPlot7, width = 10, height = 15)
ggsave('Imagens/DotPlot8.tiff', plot = DotPlot8, width = 10, height = 15)
ggsave('Imagens/DotPlot9.tiff', plot = DotPlot9, width = 10, height = 15)
ggsave('Imagens/DotPlot10.tiff', plot = DotPlot10, width = 10, height = 15)
ggsave('Imagens/DotPlot11.tiff', plot = DotPlot11, width = 10, height = 15)
ggsave('Imagens/DotPlot12.tiff', plot = DotPlot12, width = 10, height = 15)
ggsave('Imagens/DotPlot13.tiff', plot = DotPlot13, width = 10, height = 15)
ggsave('Imagens/DotPlot14.tiff', plot = DotPlot14, width = 10, height = 15)
ggsave('Imagens/DotPlot15.tiff', plot = DotPlot15, width = 10, height = 15)
ggsave('Imagens/DotPlot16.tiff', plot = DotPlot16, width = 10, height = 15)

# CENTRAL_NERVOUS_SYSTEM - ver dnv dps

DotPlot <- DotPlot(linhagens, features = lista_CIFS$V1[1:6], idents = linhagens_sample$value[20:24])
DotPlot1 <- DotPlot(linhagens, features = lista_CIFS$V1[6:11], idents = linhagens_sample$value[20:24])
DotPlot2 <- DotPlot(linhagens, features = lista_CIFS$V1[12:17], idents = linhagens_sample$value[20:24])
DotPlot3 <- DotPlot(linhagens, features = lista_CIFS$V1[18:23], idents = linhagens_sample$value[20:24])
DotPlot4 <- DotPlot(linhagens, features = lista_CIFS$V1[24:29], idents = linhagens_sample$value[20:24])
DotPlot5 <- DotPlot(linhagens, features = lista_CIFS$V1[30:35], idents = linhagens_sample$value[20:24])
DotPlot6 <- DotPlot(linhagens, features = lista_CIFS$V1[36:41], idents = linhagens_sample$value[20:24])
DotPlot7 <- DotPlot(linhagens, features = lista_CIFS$V1[42:47], idents = linhagens_sample$value[20:24])
DotPlot8 <- DotPlot(linhagens, features = lista_CIFS$V1[48:53], idents = linhagens_sample$value[20:24])
DotPlot9 <- DotPlot(linhagens, features = lista_CIFS$V1[54:59], idents = linhagens_sample$value[20:24])
DotPlot10 <- DotPlot(linhagens, features = lista_CIFS$V1[60:65], idents = linhagens_sample$value[20:24])
DotPlot11 <- DotPlot(linhagens, features = lista_CIFS$V1[66:71], idents = linhagens_sample$value[20:24])
DotPlot12 <- DotPlot(linhagens, features = lista_CIFS$V1[72:77], idents = linhagens_sample$value[20:24])
DotPlot13 <- DotPlot(linhagens, features = lista_CIFS$V1[78:83], idents = linhagens_sample$value[20:24])
DotPlot14 <- DotPlot(linhagens, features = lista_CIFS$V1[84:89], idents = linhagens_sample$value[20:24])
DotPlot15 <- DotPlot(linhagens, features = lista_CIFS$V1[90:95], idents = linhagens_sample$value[20:24])
DotPlot16<- DotPlot(linhagens, features = lista_CIFS$V1[96:102], idents = linhagens_sample$value[20:24])

ggsave('Imagens/DotPlot.tiff', plot = DotPlot, width = 10, height = 15)
ggsave('Imagens/DotPlot1.tiff', plot = DotPlot1, width = 10, height = 15)
ggsave('Imagens/DotPlot2.tiff', plot = DotPlot2, width = 10, height = 15)
ggsave('Imagens/DotPlot3.tiff', plot = DotPlot3, width = 10, height = 15)
ggsave('Imagens/DotPlot4.tiff', plot = DotPlot4, width = 10, height = 15)
ggsave('Imagens/DotPlot5.tiff', plot = DotPlot5, width = 10, height = 15)
ggsave('Imagens/DotPlot6.tiff', plot = DotPlot6, width = 10, height = 15)
ggsave('Imagens/DotPlot7.tiff', plot = DotPlot7, width = 10, height = 15)
ggsave('Imagens/DotPlot8.tiff', plot = DotPlot8, width = 10, height = 15)
ggsave('Imagens/DotPlot9.tiff', plot = DotPlot9, width = 10, height = 15)
ggsave('Imagens/DotPlot10.tiff', plot = DotPlot10, width = 10, height = 15)
ggsave('Imagens/DotPlot11.tiff', plot = DotPlot11, width = 10, height = 15)
ggsave('Imagens/DotPlot12.tiff', plot = DotPlot12, width = 10, height = 15)
ggsave('Imagens/DotPlot13.tiff', plot = DotPlot13, width = 10, height = 15)
ggsave('Imagens/DotPlot14.tiff', plot = DotPlot14, width = 10, height = 15)
ggsave('Imagens/DotPlot15.tiff', plot = DotPlot15, width = 10, height = 15)
ggsave('Imagens/DotPlot16.tiff', plot = DotPlot16, width = 10, height = 15)

# URINARY_TRACT - ver dnv dps

DotPlot <- DotPlot(linhagens, features = lista_CIFS$V1[1:6], idents = linhagens_sample$value[25:29])
DotPlot1 <- DotPlot(linhagens, features = lista_CIFS$V1[6:11], idents = linhagens_sample$value[25:29])
DotPlot2 <- DotPlot(linhagens, features = lista_CIFS$V1[12:17], idents = linhagens_sample$value[25:29])
DotPlot3 <- DotPlot(linhagens, features = lista_CIFS$V1[18:23], idents = linhagens_sample$value[25:29])
DotPlot4 <- DotPlot(linhagens, features = lista_CIFS$V1[24:29], idents = linhagens_sample$value[25:29])
DotPlot5 <- DotPlot(linhagens, features = lista_CIFS$V1[30:35], idents = linhagens_sample$value[25:29])
DotPlot6 <- DotPlot(linhagens, features = lista_CIFS$V1[36:41], idents = linhagens_sample$value[25:29])
DotPlot7 <- DotPlot(linhagens, features = lista_CIFS$V1[42:47], idents = linhagens_sample$value[25:29])
DotPlot8 <- DotPlot(linhagens, features = lista_CIFS$V1[48:53], idents = linhagens_sample$value[25:29])
DotPlot9 <- DotPlot(linhagens, features = lista_CIFS$V1[54:59], idents = linhagens_sample$value[25:29])
DotPlot10 <- DotPlot(linhagens, features = lista_CIFS$V1[60:65], idents = linhagens_sample$value[25:29])
DotPlot11 <- DotPlot(linhagens, features = lista_CIFS$V1[66:71], idents = linhagens_sample$value[25:29])
DotPlot12 <- DotPlot(linhagens, features = lista_CIFS$V1[72:77], idents = linhagens_sample$value[25:29])
DotPlot13 <- DotPlot(linhagens, features = lista_CIFS$V1[78:83], idents = linhagens_sample$value[25:29])
DotPlot14 <- DotPlot(linhagens, features = lista_CIFS$V1[84:89], idents = linhagens_sample$value[25:29])
DotPlot15 <- DotPlot(linhagens, features = lista_CIFS$V1[90:95], idents = linhagens_sample$value[25:29])
DotPlot16<- DotPlot(linhagens, features = lista_CIFS$V1[96:102], idents = linhagens_sample$value[25:29])

ggsave('Imagens/DotPlot.tiff', plot = DotPlot, width = 10, height = 15)
ggsave('Imagens/DotPlot1.tiff', plot = DotPlot1, width = 10, height = 15)
ggsave('Imagens/DotPlot2.tiff', plot = DotPlot2, width = 10, height = 15)
ggsave('Imagens/DotPlot3.tiff', plot = DotPlot3, width = 10, height = 15)
ggsave('Imagens/DotPlot4.tiff', plot = DotPlot4, width = 10, height = 15)
ggsave('Imagens/DotPlot5.tiff', plot = DotPlot5, width = 10, height = 15)
ggsave('Imagens/DotPlot6.tiff', plot = DotPlot6, width = 10, height = 15)
ggsave('Imagens/DotPlot7.tiff', plot = DotPlot7, width = 10, height = 15)
ggsave('Imagens/DotPlot8.tiff', plot = DotPlot8, width = 10, height = 15)
ggsave('Imagens/DotPlot9.tiff', plot = DotPlot9, width = 10, height = 15)
ggsave('Imagens/DotPlot10.tiff', plot = DotPlot10, width = 10, height = 15)
ggsave('Imagens/DotPlot11.tiff', plot = DotPlot11, width = 10, height = 15)
ggsave('Imagens/DotPlot12.tiff', plot = DotPlot12, width = 10, height = 15)
ggsave('Imagens/DotPlot13.tiff', plot = DotPlot13, width = 10, height = 15)
ggsave('Imagens/DotPlot14.tiff', plot = DotPlot14, width = 10, height = 15)
ggsave('Imagens/DotPlot15.tiff', plot = DotPlot15, width = 10, height = 15)
ggsave('Imagens/DotPlot16.tiff', plot = DotPlot16, width = 10, height = 15)

# BILIARY_TRACT

DotPlot <- DotPlot(linhagens, features = lista_CIFS$V1[1:6], idents = linhagens_sample$value[30:34])
DotPlot1 <- DotPlot(linhagens, features = lista_CIFS$V1[6:11], idents = linhagens_sample$value[30:34])
DotPlot2 <- DotPlot(linhagens, features = lista_CIFS$V1[12:17], idents = linhagens_sample$value[30:34])
DotPlot3 <- DotPlot(linhagens, features = lista_CIFS$V1[18:23], idents = linhagens_sample$value[30:34])
DotPlot4 <- DotPlot(linhagens, features = lista_CIFS$V1[24:29], idents = linhagens_sample$value[30:34])
DotPlot5 <- DotPlot(linhagens, features = lista_CIFS$V1[30:35], idents = linhagens_sample$value[30:34])
DotPlot6 <- DotPlot(linhagens, features = lista_CIFS$V1[36:41], idents = linhagens_sample$value[30:34])
DotPlot7 <- DotPlot(linhagens, features = lista_CIFS$V1[42:47], idents = linhagens_sample$value[30:34])
DotPlot8 <- DotPlot(linhagens, features = lista_CIFS$V1[48:53], idents = linhagens_sample$value[30:34])
DotPlot9 <- DotPlot(linhagens, features = lista_CIFS$V1[54:59], idents = linhagens_sample$value[30:34])
DotPlot10 <- DotPlot(linhagens, features = lista_CIFS$V1[60:65], idents = linhagens_sample$value[30:34])
DotPlot11 <- DotPlot(linhagens, features = lista_CIFS$V1[66:71], idents = linhagens_sample$value[30:34])
DotPlot12 <- DotPlot(linhagens, features = lista_CIFS$V1[72:77], idents = linhagens_sample$value[30:34])
DotPlot13 <- DotPlot(linhagens, features = lista_CIFS$V1[78:83], idents = linhagens_sample$value[30:34])
DotPlot14 <- DotPlot(linhagens, features = lista_CIFS$V1[84:89], idents = linhagens_sample$value[30:34])
DotPlot15 <- DotPlot(linhagens, features = lista_CIFS$V1[90:95], idents = linhagens_sample$value[30:34])
DotPlot16<- DotPlot(linhagens, features = lista_CIFS$V1[96:102], idents = linhagens_sample$value[30:34])

ggsave('Imagens/DotPlot.tiff', plot = DotPlot, width = 10, height = 15)
ggsave('Imagens/DotPlot1.tiff', plot = DotPlot1, width = 10, height = 15)
ggsave('Imagens/DotPlot2.tiff', plot = DotPlot2, width = 10, height = 15)
ggsave('Imagens/DotPlot3.tiff', plot = DotPlot3, width = 10, height = 15)
ggsave('Imagens/DotPlot4.tiff', plot = DotPlot4, width = 10, height = 15)
ggsave('Imagens/DotPlot5.tiff', plot = DotPlot5, width = 10, height = 15)
ggsave('Imagens/DotPlot6.tiff', plot = DotPlot6, width = 10, height = 15)
ggsave('Imagens/DotPlot7.tiff', plot = DotPlot7, width = 10, height = 15)
ggsave('Imagens/DotPlot8.tiff', plot = DotPlot8, width = 10, height = 15)
ggsave('Imagens/DotPlot9.tiff', plot = DotPlot9, width = 10, height = 15)
ggsave('Imagens/DotPlot10.tiff', plot = DotPlot10, width = 10, height = 15)
ggsave('Imagens/DotPlot11.tiff', plot = DotPlot11, width = 10, height = 15)
ggsave('Imagens/DotPlot12.tiff', plot = DotPlot12, width = 10, height = 15)
ggsave('Imagens/DotPlot13.tiff', plot = DotPlot13, width = 10, height = 15)
ggsave('Imagens/DotPlot14.tiff', plot = DotPlot14, width = 10, height = 15)
ggsave('Imagens/DotPlot15.tiff', plot = DotPlot15, width = 10, height = 15)
ggsave('Imagens/DotPlot16.tiff', plot = DotPlot16, width = 10, height = 15)

# BREAST

DotPlot <- DotPlot(linhagens, features = lista_CIFS$V1[1:6], idents = linhagens_sample$value[35:39])
DotPlot1 <- DotPlot(linhagens, features = lista_CIFS$V1[6:11], idents = linhagens_sample$value[35:39])
DotPlot2 <- DotPlot(linhagens, features = lista_CIFS$V1[12:17], idents = linhagens_sample$value[35:39])
DotPlot3 <- DotPlot(linhagens, features = lista_CIFS$V1[18:23], idents = linhagens_sample$value[35:39])
DotPlot4 <- DotPlot(linhagens, features = lista_CIFS$V1[24:29], idents = linhagens_sample$value[35:39])
DotPlot5 <- DotPlot(linhagens, features = lista_CIFS$V1[30:35], idents = linhagens_sample$value[35:39])
DotPlot6 <- DotPlot(linhagens, features = lista_CIFS$V1[36:41], idents = linhagens_sample$value[35:39])
DotPlot7 <- DotPlot(linhagens, features = lista_CIFS$V1[42:47], idents = linhagens_sample$value[35:39])
DotPlot8 <- DotPlot(linhagens, features = lista_CIFS$V1[48:53], idents = linhagens_sample$value[35:39])
DotPlot9 <- DotPlot(linhagens, features = lista_CIFS$V1[54:59], idents = linhagens_sample$value[35:39])
DotPlot10 <- DotPlot(linhagens, features = lista_CIFS$V1[60:65], idents = linhagens_sample$value[35:39])
DotPlot11 <- DotPlot(linhagens, features = lista_CIFS$V1[66:71], idents = linhagens_sample$value[35:39])
DotPlot12 <- DotPlot(linhagens, features = lista_CIFS$V1[72:77], idents = linhagens_sample$value[35:39])
DotPlot13 <- DotPlot(linhagens, features = lista_CIFS$V1[78:83], idents = linhagens_sample$value[35:39])
DotPlot14 <- DotPlot(linhagens, features = lista_CIFS$V1[84:89], idents = linhagens_sample$value[35:39])
DotPlot15 <- DotPlot(linhagens, features = lista_CIFS$V1[90:95], idents = linhagens_sample$value[35:39])
DotPlot16<- DotPlot(linhagens, features = lista_CIFS$V1[96:102], idents = linhagens_sample$value[35:39])

ggsave('Imagens/DotPlot.tiff', plot = DotPlot, width = 10, height = 15)
ggsave('Imagens/DotPlot1.tiff', plot = DotPlot1, width = 10, height = 15)
ggsave('Imagens/DotPlot2.tiff', plot = DotPlot2, width = 10, height = 15)
ggsave('Imagens/DotPlot3.tiff', plot = DotPlot3, width = 10, height = 15)
ggsave('Imagens/DotPlot4.tiff', plot = DotPlot4, width = 10, height = 15)
ggsave('Imagens/DotPlot5.tiff', plot = DotPlot5, width = 10, height = 15)
ggsave('Imagens/DotPlot6.tiff', plot = DotPlot6, width = 10, height = 15)
ggsave('Imagens/DotPlot7.tiff', plot = DotPlot7, width = 10, height = 15)
ggsave('Imagens/DotPlot8.tiff', plot = DotPlot8, width = 10, height = 15)
ggsave('Imagens/DotPlot9.tiff', plot = DotPlot9, width = 10, height = 15)
ggsave('Imagens/DotPlot10.tiff', plot = DotPlot10, width = 10, height = 15)
ggsave('Imagens/DotPlot11.tiff', plot = DotPlot11, width = 10, height = 15)
ggsave('Imagens/DotPlot12.tiff', plot = DotPlot12, width = 10, height = 15)
ggsave('Imagens/DotPlot13.tiff', plot = DotPlot13, width = 10, height = 15)
ggsave('Imagens/DotPlot14.tiff', plot = DotPlot14, width = 10, height = 15)
ggsave('Imagens/DotPlot15.tiff', plot = DotPlot15, width = 10, height = 15)
ggsave('Imagens/DotPlot16.tiff', plot = DotPlot16, width = 10, height = 15)

# UPPER_AERODIGESTIVE_TRACT - ver dnv dps

DotPlot <- DotPlot(linhagens, features = lista_CIFS$V1[1:6], idents = linhagens_sample$value[40:44])
DotPlot1 <- DotPlot(linhagens, features = lista_CIFS$V1[6:11], idents = linhagens_sample$value[40:44])
DotPlot2 <- DotPlot(linhagens, features = lista_CIFS$V1[12:17], idents = linhagens_sample$value[40:44])
DotPlot3 <- DotPlot(linhagens, features = lista_CIFS$V1[18:23], idents = linhagens_sample$value[40:44])
DotPlot4 <- DotPlot(linhagens, features = lista_CIFS$V1[24:29], idents = linhagens_sample$value[40:44])
DotPlot5 <- DotPlot(linhagens, features = lista_CIFS$V1[30:35], idents = linhagens_sample$value[40:44])
DotPlot6 <- DotPlot(linhagens, features = lista_CIFS$V1[36:41], idents = linhagens_sample$value[40:44])
DotPlot7 <- DotPlot(linhagens, features = lista_CIFS$V1[42:47], idents = linhagens_sample$value[40:44])
DotPlot8 <- DotPlot(linhagens, features = lista_CIFS$V1[48:53], idents = linhagens_sample$value[40:44])
DotPlot9 <- DotPlot(linhagens, features = lista_CIFS$V1[54:59], idents = linhagens_sample$value[40:44])
DotPlot10 <- DotPlot(linhagens, features = lista_CIFS$V1[60:65], idents = linhagens_sample$value[40:44])
DotPlot11 <- DotPlot(linhagens, features = lista_CIFS$V1[66:71], idents = linhagens_sample$value[40:44])
DotPlot12 <- DotPlot(linhagens, features = lista_CIFS$V1[72:77], idents = linhagens_sample$value[40:44])
DotPlot13 <- DotPlot(linhagens, features = lista_CIFS$V1[78:83], idents = linhagens_sample$value[40:44])
DotPlot14 <- DotPlot(linhagens, features = lista_CIFS$V1[84:89], idents = linhagens_sample$value[40:44])
DotPlot15 <- DotPlot(linhagens, features = lista_CIFS$V1[90:95], idents = linhagens_sample$value[40:44])
DotPlot16<- DotPlot(linhagens, features = lista_CIFS$V1[96:102], idents = linhagens_sample$value[40:44])

ggsave('Imagens/DotPlot.tiff', plot = DotPlot, width = 10, height = 15)
ggsave('Imagens/DotPlot1.tiff', plot = DotPlot1, width = 10, height = 15)
ggsave('Imagens/DotPlot2.tiff', plot = DotPlot2, width = 10, height = 15)
ggsave('Imagens/DotPlot3.tiff', plot = DotPlot3, width = 10, height = 15)
ggsave('Imagens/DotPlot4.tiff', plot = DotPlot4, width = 10, height = 15)
ggsave('Imagens/DotPlot5.tiff', plot = DotPlot5, width = 10, height = 15)
ggsave('Imagens/DotPlot6.tiff', plot = DotPlot6, width = 10, height = 15)
ggsave('Imagens/DotPlot7.tiff', plot = DotPlot7, width = 10, height = 15)
ggsave('Imagens/DotPlot8.tiff', plot = DotPlot8, width = 10, height = 15)
ggsave('Imagens/DotPlot9.tiff', plot = DotPlot9, width = 10, height = 15)
ggsave('Imagens/DotPlot10.tiff', plot = DotPlot10, width = 10, height = 15)
ggsave('Imagens/DotPlot11.tiff', plot = DotPlot11, width = 10, height = 15)
ggsave('Imagens/DotPlot12.tiff', plot = DotPlot12, width = 10, height = 15)
ggsave('Imagens/DotPlot13.tiff', plot = DotPlot13, width = 10, height = 15)
ggsave('Imagens/DotPlot14.tiff', plot = DotPlot14, width = 10, height = 15)
ggsave('Imagens/DotPlot15.tiff', plot = DotPlot15, width = 10, height = 15)
ggsave('Imagens/DotPlot16.tiff', plot = DotPlot16, width = 10, height = 15)

# STOMACH

DotPlot <- DotPlot(linhagens, features = lista_CIFS$V1[1:6], idents = linhagens_sample$value[45:49])
DotPlot1 <- DotPlot(linhagens, features = lista_CIFS$V1[6:11], idents = linhagens_sample$value[45:49])
DotPlot2 <- DotPlot(linhagens, features = lista_CIFS$V1[12:17], idents = linhagens_sample$value[45:49])
DotPlot3 <- DotPlot(linhagens, features = lista_CIFS$V1[18:23], idents = linhagens_sample$value[45:49])
DotPlot4 <- DotPlot(linhagens, features = lista_CIFS$V1[24:29], idents = linhagens_sample$value[45:49])
DotPlot5 <- DotPlot(linhagens, features = lista_CIFS$V1[30:35], idents = linhagens_sample$value[45:49])
DotPlot6 <- DotPlot(linhagens, features = lista_CIFS$V1[36:41], idents = linhagens_sample$value[45:49])
DotPlot7 <- DotPlot(linhagens, features = lista_CIFS$V1[42:47], idents = linhagens_sample$value[45:49])
DotPlot8 <- DotPlot(linhagens, features = lista_CIFS$V1[48:53], idents = linhagens_sample$value[45:49])
DotPlot9 <- DotPlot(linhagens, features = lista_CIFS$V1[54:59], idents = linhagens_sample$value[45:49])
DotPlot10 <- DotPlot(linhagens, features = lista_CIFS$V1[60:65], idents = linhagens_sample$value[45:49])
DotPlot11 <- DotPlot(linhagens, features = lista_CIFS$V1[66:71], idents = linhagens_sample$value[45:49])
DotPlot12 <- DotPlot(linhagens, features = lista_CIFS$V1[72:77], idents = linhagens_sample$value[45:49])
DotPlot13 <- DotPlot(linhagens, features = lista_CIFS$V1[78:83], idents = linhagens_sample$value[45:49])
DotPlot14 <- DotPlot(linhagens, features = lista_CIFS$V1[84:89], idents = linhagens_sample$value[45:49])
DotPlot15 <- DotPlot(linhagens, features = lista_CIFS$V1[90:95], idents = linhagens_sample$value[45:49])
DotPlot16<- DotPlot(linhagens, features = lista_CIFS$V1[96:102], idents = linhagens_sample$value[45:49])

ggsave('Imagens/DotPlot.tiff', plot = DotPlot, width = 10, height = 15)
ggsave('Imagens/DotPlot1.tiff', plot = DotPlot1, width = 10, height = 15)
ggsave('Imagens/DotPlot2.tiff', plot = DotPlot2, width = 10, height = 15)
ggsave('Imagens/DotPlot3.tiff', plot = DotPlot3, width = 10, height = 15)
ggsave('Imagens/DotPlot4.tiff', plot = DotPlot4, width = 10, height = 15)
ggsave('Imagens/DotPlot5.tiff', plot = DotPlot5, width = 10, height = 15)
ggsave('Imagens/DotPlot6.tiff', plot = DotPlot6, width = 10, height = 15)
ggsave('Imagens/DotPlot7.tiff', plot = DotPlot7, width = 10, height = 15)
ggsave('Imagens/DotPlot8.tiff', plot = DotPlot8, width = 10, height = 15)
ggsave('Imagens/DotPlot9.tiff', plot = DotPlot9, width = 10, height = 15)
ggsave('Imagens/DotPlot10.tiff', plot = DotPlot10, width = 10, height = 15)
ggsave('Imagens/DotPlot11.tiff', plot = DotPlot11, width = 10, height = 15)
ggsave('Imagens/DotPlot12.tiff', plot = DotPlot12, width = 10, height = 15)
ggsave('Imagens/DotPlot13.tiff', plot = DotPlot13, width = 10, height = 15)
ggsave('Imagens/DotPlot14.tiff', plot = DotPlot14, width = 10, height = 15)
ggsave('Imagens/DotPlot15.tiff', plot = DotPlot15, width = 10, height = 15)
ggsave('Imagens/DotPlot16.tiff', plot = DotPlot16, width = 10, height = 15)

# LARGE_INSTETINE

DotPlot <- DotPlot(linhagens, features = lista_CIFS$V1[1:6], idents = linhagens_sample$value[50:54])
DotPlot1 <- DotPlot(linhagens, features = lista_CIFS$V1[6:11], idents = linhagens_sample$value[50:54])
DotPlot2 <- DotPlot(linhagens, features = lista_CIFS$V1[12:17], idents = linhagens_sample$value[50:54])
DotPlot3 <- DotPlot(linhagens, features = lista_CIFS$V1[18:23], idents = linhagens_sample$value[50:54])
DotPlot4 <- DotPlot(linhagens, features = lista_CIFS$V1[24:29], idents = linhagens_sample$value[50:54])
DotPlot5 <- DotPlot(linhagens, features = lista_CIFS$V1[30:35], idents = linhagens_sample$value[50:54])
DotPlot6 <- DotPlot(linhagens, features = lista_CIFS$V1[36:41], idents = linhagens_sample$value[50:54])
DotPlot7 <- DotPlot(linhagens, features = lista_CIFS$V1[42:47], idents = linhagens_sample$value[50:54])
DotPlot8 <- DotPlot(linhagens, features = lista_CIFS$V1[48:53], idents = linhagens_sample$value[50:54])
DotPlot9 <- DotPlot(linhagens, features = lista_CIFS$V1[54:59], idents = linhagens_sample$value[50:54])
DotPlot10 <- DotPlot(linhagens, features = lista_CIFS$V1[60:65], idents = linhagens_sample$value[50:54])
DotPlot11 <- DotPlot(linhagens, features = lista_CIFS$V1[66:71], idents = linhagens_sample$value[50:54])
DotPlot12 <- DotPlot(linhagens, features = lista_CIFS$V1[72:77], idents = linhagens_sample$value[50:54])
DotPlot13 <- DotPlot(linhagens, features = lista_CIFS$V1[78:83], idents = linhagens_sample$value[50:54])
DotPlot14 <- DotPlot(linhagens, features = lista_CIFS$V1[84:89], idents = linhagens_sample$value[50:54])
DotPlot15 <- DotPlot(linhagens, features = lista_CIFS$V1[90:95], idents = linhagens_sample$value[50:54])
DotPlot16<- DotPlot(linhagens, features = lista_CIFS$V1[96:102], idents = linhagens_sample$value[50:54])

ggsave('Imagens/DotPlot.tiff', plot = DotPlot, width = 10, height = 15)
ggsave('Imagens/DotPlot1.tiff', plot = DotPlot1, width = 10, height = 15)
ggsave('Imagens/DotPlot2.tiff', plot = DotPlot2, width = 10, height = 15)
ggsave('Imagens/DotPlot3.tiff', plot = DotPlot3, width = 10, height = 15)
ggsave('Imagens/DotPlot4.tiff', plot = DotPlot4, width = 10, height = 15)
ggsave('Imagens/DotPlot5.tiff', plot = DotPlot5, width = 10, height = 15)
ggsave('Imagens/DotPlot6.tiff', plot = DotPlot6, width = 10, height = 15)
ggsave('Imagens/DotPlot7.tiff', plot = DotPlot7, width = 10, height = 15)
ggsave('Imagens/DotPlot8.tiff', plot = DotPlot8, width = 10, height = 15)
ggsave('Imagens/DotPlot9.tiff', plot = DotPlot9, width = 10, height = 15)
ggsave('Imagens/DotPlot10.tiff', plot = DotPlot10, width = 10, height = 15)
ggsave('Imagens/DotPlot11.tiff', plot = DotPlot11, width = 10, height = 15)
ggsave('Imagens/DotPlot12.tiff', plot = DotPlot12, width = 10, height = 15)
ggsave('Imagens/DotPlot13.tiff', plot = DotPlot13, width = 10, height = 15)
ggsave('Imagens/DotPlot14.tiff', plot = DotPlot14, width = 10, height = 15)
ggsave('Imagens/DotPlot15.tiff', plot = DotPlot15, width = 10, height = 15)
ggsave('Imagens/DotPlot16.tiff', plot = DotPlot16, width = 10, height = 15)

# PROSTATE - ver dnv dps

DotPlot <- DotPlot(linhagens, features = lista_CIFS$V1[1:6], idents = linhagens_sample$value[55:56])
DotPlot1 <- DotPlot(linhagens, features = lista_CIFS$V1[6:11], idents = linhagens_sample$value[55:56])
DotPlot2 <- DotPlot(linhagens, features = lista_CIFS$V1[12:17], idents = linhagens_sample$value[55:56])
DotPlot3 <- DotPlot(linhagens, features = lista_CIFS$V1[18:23], idents = linhagens_sample$value[55:56])
DotPlot4 <- DotPlot(linhagens, features = lista_CIFS$V1[24:29], idents = linhagens_sample$value[55:56])
DotPlot5 <- DotPlot(linhagens, features = lista_CIFS$V1[30:35], idents = linhagens_sample$value[55:56])
DotPlot6 <- DotPlot(linhagens, features = lista_CIFS$V1[36:41], idents = linhagens_sample$value[55:56])
DotPlot7 <- DotPlot(linhagens, features = lista_CIFS$V1[42:47], idents = linhagens_sample$value[55:56])
DotPlot8 <- DotPlot(linhagens, features = lista_CIFS$V1[48:53], idents = linhagens_sample$value[55:56])
DotPlot9 <- DotPlot(linhagens, features = lista_CIFS$V1[54:59], idents = linhagens_sample$value[55:56])
DotPlot10 <- DotPlot(linhagens, features = lista_CIFS$V1[60:65], idents = linhagens_sample$value[55:56])
DotPlot11 <- DotPlot(linhagens, features = lista_CIFS$V1[66:71], idents = linhagens_sample$value[55:56])
DotPlot12 <- DotPlot(linhagens, features = lista_CIFS$V1[72:77], idents = linhagens_sample$value[55:56])
DotPlot13 <- DotPlot(linhagens, features = lista_CIFS$V1[78:83], idents = linhagens_sample$value[55:56])
DotPlot14 <- DotPlot(linhagens, features = lista_CIFS$V1[84:89], idents = linhagens_sample$value[55:56])
DotPlot15 <- DotPlot(linhagens, features = lista_CIFS$V1[90:95], idents = linhagens_sample$value[55:56])
DotPlot16<- DotPlot(linhagens, features = lista_CIFS$V1[96:102], idents = linhagens_sample$value[55:56])

ggsave('Imagens/DotPlot.tiff', plot = DotPlot, width = 10, height = 15)
ggsave('Imagens/DotPlot1.tiff', plot = DotPlot1, width = 10, height = 15)
ggsave('Imagens/DotPlot2.tiff', plot = DotPlot2, width = 10, height = 15)
ggsave('Imagens/DotPlot3.tiff', plot = DotPlot3, width = 10, height = 15)
ggsave('Imagens/DotPlot4.tiff', plot = DotPlot4, width = 10, height = 15)
ggsave('Imagens/DotPlot5.tiff', plot = DotPlot5, width = 10, height = 15)
ggsave('Imagens/DotPlot6.tiff', plot = DotPlot6, width = 10, height = 15)
ggsave('Imagens/DotPlot7.tiff', plot = DotPlot7, width = 10, height = 15)
ggsave('Imagens/DotPlot8.tiff', plot = DotPlot8, width = 10, height = 15)
ggsave('Imagens/DotPlot9.tiff', plot = DotPlot9, width = 10, height = 15)
ggsave('Imagens/DotPlot10.tiff', plot = DotPlot10, width = 10, height = 15)
ggsave('Imagens/DotPlot11.tiff', plot = DotPlot11, width = 10, height = 15)
ggsave('Imagens/DotPlot12.tiff', plot = DotPlot12, width = 10, height = 15)
ggsave('Imagens/DotPlot13.tiff', plot = DotPlot13, width = 10, height = 15)
ggsave('Imagens/DotPlot14.tiff', plot = DotPlot14, width = 10, height = 15)
ggsave('Imagens/DotPlot15.tiff', plot = DotPlot15, width = 10, height = 15)
ggsave('Imagens/DotPlot16.tiff', plot = DotPlot16, width = 10, height = 15)

# KIDNEY

DotPlot <- DotPlot(linhagens, features = lista_CIFS$V1[1:6], idents = linhagens_sample$value[57:61])
DotPlot1 <- DotPlot(linhagens, features = lista_CIFS$V1[6:11], idents = linhagens_sample$value[57:61])
DotPlot2 <- DotPlot(linhagens, features = lista_CIFS$V1[12:17], idents = linhagens_sample$value[57:61])
DotPlot3 <- DotPlot(linhagens, features = lista_CIFS$V1[18:23], idents = linhagens_sample$value[57:61])
DotPlot4 <- DotPlot(linhagens, features = lista_CIFS$V1[24:29], idents = linhagens_sample$value[57:61])
DotPlot5 <- DotPlot(linhagens, features = lista_CIFS$V1[30:35], idents = linhagens_sample$value[57:61])
DotPlot6 <- DotPlot(linhagens, features = lista_CIFS$V1[36:41], idents = linhagens_sample$value[57:61])
DotPlot7 <- DotPlot(linhagens, features = lista_CIFS$V1[42:47], idents = linhagens_sample$value[57:61])
DotPlot8 <- DotPlot(linhagens, features = lista_CIFS$V1[48:53], idents = linhagens_sample$value[57:61])
DotPlot9 <- DotPlot(linhagens, features = lista_CIFS$V1[54:59], idents = linhagens_sample$value[57:61])
DotPlot10 <- DotPlot(linhagens, features = lista_CIFS$V1[60:65], idents = linhagens_sample$value[57:61])
DotPlot11 <- DotPlot(linhagens, features = lista_CIFS$V1[66:71], idents = linhagens_sample$value[57:61])
DotPlot12 <- DotPlot(linhagens, features = lista_CIFS$V1[72:77], idents = linhagens_sample$value[57:61])
DotPlot13 <- DotPlot(linhagens, features = lista_CIFS$V1[78:83], idents = linhagens_sample$value[57:61])
DotPlot14 <- DotPlot(linhagens, features = lista_CIFS$V1[84:89], idents = linhagens_sample$value[57:61])
DotPlot15 <- DotPlot(linhagens, features = lista_CIFS$V1[90:95], idents = linhagens_sample$value[57:61])
DotPlot16<- DotPlot(linhagens, features = lista_CIFS$V1[96:102], idents = linhagens_sample$value[57:61])

ggsave('Imagens/DotPlot.tiff', plot = DotPlot, width = 10, height = 15)
ggsave('Imagens/DotPlot1.tiff', plot = DotPlot1, width = 10, height = 15)
ggsave('Imagens/DotPlot2.tiff', plot = DotPlot2, width = 10, height = 15)
ggsave('Imagens/DotPlot3.tiff', plot = DotPlot3, width = 10, height = 15)
ggsave('Imagens/DotPlot4.tiff', plot = DotPlot4, width = 10, height = 15)
ggsave('Imagens/DotPlot5.tiff', plot = DotPlot5, width = 10, height = 15)
ggsave('Imagens/DotPlot6.tiff', plot = DotPlot6, width = 10, height = 15)
ggsave('Imagens/DotPlot7.tiff', plot = DotPlot7, width = 10, height = 15)
ggsave('Imagens/DotPlot8.tiff', plot = DotPlot8, width = 10, height = 15)
ggsave('Imagens/DotPlot9.tiff', plot = DotPlot9, width = 10, height = 15)
ggsave('Imagens/DotPlot10.tiff', plot = DotPlot10, width = 10, height = 15)
ggsave('Imagens/DotPlot11.tiff', plot = DotPlot11, width = 10, height = 15)
ggsave('Imagens/DotPlot12.tiff', plot = DotPlot12, width = 10, height = 15)
ggsave('Imagens/DotPlot13.tiff', plot = DotPlot13, width = 10, height = 15)
ggsave('Imagens/DotPlot14.tiff', plot = DotPlot14, width = 10, height = 15)
ggsave('Imagens/DotPlot15.tiff', plot = DotPlot15, width = 10, height = 15)
ggsave('Imagens/DotPlot16.tiff', plot = DotPlot16, width = 10, height = 15)

# LUNG

DotPlot <- DotPlot(linhagens, features = lista_CIFS$V1[1:6], idents = linhagens_sample$value[62:66])
DotPlot1 <- DotPlot(linhagens, features = lista_CIFS$V1[6:11], idents = linhagens_sample$value[62:66])
DotPlot2 <- DotPlot(linhagens, features = lista_CIFS$V1[12:17], idents = linhagens_sample$value[62:66])
DotPlot3 <- DotPlot(linhagens, features = lista_CIFS$V1[18:23], idents = linhagens_sample$value[62:66])
DotPlot4 <- DotPlot(linhagens, features = lista_CIFS$V1[24:29], idents = linhagens_sample$value[62:66])
DotPlot5 <- DotPlot(linhagens, features = lista_CIFS$V1[30:35], idents = linhagens_sample$value[62:66])
DotPlot6 <- DotPlot(linhagens, features = lista_CIFS$V1[36:41], idents = linhagens_sample$value[62:66])
DotPlot7 <- DotPlot(linhagens, features = lista_CIFS$V1[42:47], idents = linhagens_sample$value[62:66])
DotPlot8 <- DotPlot(linhagens, features = lista_CIFS$V1[48:53], idents = linhagens_sample$value[62:66])
DotPlot9 <- DotPlot(linhagens, features = lista_CIFS$V1[54:59], idents = linhagens_sample$value[62:66])
DotPlot10 <- DotPlot(linhagens, features = lista_CIFS$V1[60:65], idents = linhagens_sample$value[62:66])
DotPlot11 <- DotPlot(linhagens, features = lista_CIFS$V1[66:71], idents = linhagens_sample$value[62:66])
DotPlot12 <- DotPlot(linhagens, features = lista_CIFS$V1[72:77], idents = linhagens_sample$value[62:66])
DotPlot13 <- DotPlot(linhagens, features = lista_CIFS$V1[78:83], idents = linhagens_sample$value[62:66])
DotPlot14 <- DotPlot(linhagens, features = lista_CIFS$V1[84:89], idents = linhagens_sample$value[62:66])
DotPlot15 <- DotPlot(linhagens, features = lista_CIFS$V1[90:95], idents = linhagens_sample$value[62:66])
DotPlot16<- DotPlot(linhagens, features = lista_CIFS$V1[96:102], idents = linhagens_sample$value[62:66])

ggsave('Imagens/DotPlot.tiff', plot = DotPlot, width = 10, height = 15)
ggsave('Imagens/DotPlot1.tiff', plot = DotPlot1, width = 10, height = 15)
ggsave('Imagens/DotPlot2.tiff', plot = DotPlot2, width = 10, height = 15)
ggsave('Imagens/DotPlot3.tiff', plot = DotPlot3, width = 10, height = 15)
ggsave('Imagens/DotPlot4.tiff', plot = DotPlot4, width = 10, height = 15)
ggsave('Imagens/DotPlot5.tiff', plot = DotPlot5, width = 10, height = 15)
ggsave('Imagens/DotPlot6.tiff', plot = DotPlot6, width = 10, height = 15)
ggsave('Imagens/DotPlot7.tiff', plot = DotPlot7, width = 10, height = 15)
ggsave('Imagens/DotPlot8.tiff', plot = DotPlot8, width = 10, height = 15)
ggsave('Imagens/DotPlot9.tiff', plot = DotPlot9, width = 10, height = 15)
ggsave('Imagens/DotPlot10.tiff', plot = DotPlot10, width = 10, height = 15)
ggsave('Imagens/DotPlot11.tiff', plot = DotPlot11, width = 10, height = 15)
ggsave('Imagens/DotPlot12.tiff', plot = DotPlot12, width = 10, height = 15)
ggsave('Imagens/DotPlot13.tiff', plot = DotPlot13, width = 10, height = 15)
ggsave('Imagens/DotPlot14.tiff', plot = DotPlot14, width = 10, height = 15)
ggsave('Imagens/DotPlot15.tiff', plot = DotPlot15, width = 10, height = 15)
ggsave('Imagens/DotPlot16.tiff', plot = DotPlot16, width = 10, height = 15)

# BONE

DotPlot <- DotPlot(linhagens, features = lista_CIFS$V1[1:6], idents = linhagens_sample$value[67:69])
DotPlot1 <- DotPlot(linhagens, features = lista_CIFS$V1[6:11], idents = linhagens_sample$value[67:69])
DotPlot2 <- DotPlot(linhagens, features = lista_CIFS$V1[12:17], idents = linhagens_sample$value[67:69])
DotPlot3 <- DotPlot(linhagens, features = lista_CIFS$V1[18:23], idents = linhagens_sample$value[67:69])
DotPlot4 <- DotPlot(linhagens, features = lista_CIFS$V1[24:29], idents = linhagens_sample$value[67:69])
DotPlot5 <- DotPlot(linhagens, features = lista_CIFS$V1[30:35], idents = linhagens_sample$value[67:69])
DotPlot6 <- DotPlot(linhagens, features = lista_CIFS$V1[36:41], idents = linhagens_sample$value[67:69])
DotPlot7 <- DotPlot(linhagens, features = lista_CIFS$V1[42:47], idents = linhagens_sample$value[67:69])
DotPlot8 <- DotPlot(linhagens, features = lista_CIFS$V1[48:53], idents = linhagens_sample$value[67:69])
DotPlot9 <- DotPlot(linhagens, features = lista_CIFS$V1[54:59], idents = linhagens_sample$value[67:69])
DotPlot10 <- DotPlot(linhagens, features = lista_CIFS$V1[60:65], idents = linhagens_sample$value[67:69])
DotPlot11 <- DotPlot(linhagens, features = lista_CIFS$V1[66:71], idents = linhagens_sample$value[67:69])
DotPlot12 <- DotPlot(linhagens, features = lista_CIFS$V1[72:77], idents = linhagens_sample$value[67:69])
DotPlot13 <- DotPlot(linhagens, features = lista_CIFS$V1[78:83], idents = linhagens_sample$value[67:69])
DotPlot14 <- DotPlot(linhagens, features = lista_CIFS$V1[84:89], idents = linhagens_sample$value[67:69])
DotPlot15 <- DotPlot(linhagens, features = lista_CIFS$V1[90:95], idents = linhagens_sample$value[67:69])
DotPlot16<- DotPlot(linhagens, features = lista_CIFS$V1[96:102], idents = linhagens_sample$value[67:69])

ggsave('Imagens/DotPlot.tiff', plot = DotPlot, width = 10, height = 15)
ggsave('Imagens/DotPlot1.tiff', plot = DotPlot1, width = 10, height = 15)
ggsave('Imagens/DotPlot2.tiff', plot = DotPlot2, width = 10, height = 15)
ggsave('Imagens/DotPlot3.tiff', plot = DotPlot3, width = 10, height = 15)
ggsave('Imagens/DotPlot4.tiff', plot = DotPlot4, width = 10, height = 15)
ggsave('Imagens/DotPlot5.tiff', plot = DotPlot5, width = 10, height = 15)
ggsave('Imagens/DotPlot6.tiff', plot = DotPlot6, width = 10, height = 15)
ggsave('Imagens/DotPlot7.tiff', plot = DotPlot7, width = 10, height = 15)
ggsave('Imagens/DotPlot8.tiff', plot = DotPlot8, width = 10, height = 15)
ggsave('Imagens/DotPlot9.tiff', plot = DotPlot9, width = 10, height = 15)
ggsave('Imagens/DotPlot10.tiff', plot = DotPlot10, width = 10, height = 15)
ggsave('Imagens/DotPlot11.tiff', plot = DotPlot11, width = 10, height = 15)
ggsave('Imagens/DotPlot12.tiff', plot = DotPlot12, width = 10, height = 15)
ggsave('Imagens/DotPlot13.tiff', plot = DotPlot13, width = 10, height = 15)
ggsave('Imagens/DotPlot14.tiff', plot = DotPlot14, width = 10, height = 15)
ggsave('Imagens/DotPlot15.tiff', plot = DotPlot15, width = 10, height = 15)
ggsave('Imagens/DotPlot16.tiff', plot = DotPlot16, width = 10, height = 15)

# PANCREAS

DotPlot <- DotPlot(linhagens, features = lista_CIFS$V1[1:6], idents = linhagens_sample$value[70:74])
DotPlot1 <- DotPlot(linhagens, features = lista_CIFS$V1[6:11], idents = linhagens_sample$value[70:74])
DotPlot2 <- DotPlot(linhagens, features = lista_CIFS$V1[12:17], idents = linhagens_sample$value[70:74])
DotPlot3 <- DotPlot(linhagens, features = lista_CIFS$V1[18:23], idents = linhagens_sample$value[70:74])
DotPlot4 <- DotPlot(linhagens, features = lista_CIFS$V1[24:29], idents = linhagens_sample$value[70:74])
DotPlot5 <- DotPlot(linhagens, features = lista_CIFS$V1[30:35], idents = linhagens_sample$value[70:74])
DotPlot6 <- DotPlot(linhagens, features = lista_CIFS$V1[36:41], idents = linhagens_sample$value[70:74])
DotPlot7 <- DotPlot(linhagens, features = lista_CIFS$V1[42:47], idents = linhagens_sample$value[70:74])
DotPlot8 <- DotPlot(linhagens, features = lista_CIFS$V1[48:53], idents = linhagens_sample$value[70:74])
DotPlot9 <- DotPlot(linhagens, features = lista_CIFS$V1[54:59], idents = linhagens_sample$value[70:74])
DotPlot10 <- DotPlot(linhagens, features = lista_CIFS$V1[60:65], idents = linhagens_sample$value[70:74])
DotPlot11 <- DotPlot(linhagens, features = lista_CIFS$V1[66:71], idents = linhagens_sample$value[70:74])
DotPlot12 <- DotPlot(linhagens, features = lista_CIFS$V1[72:77], idents = linhagens_sample$value[70:74])
DotPlot13 <- DotPlot(linhagens, features = lista_CIFS$V1[78:83], idents = linhagens_sample$value[70:74])
DotPlot14 <- DotPlot(linhagens, features = lista_CIFS$V1[84:89], idents = linhagens_sample$value[70:74])
DotPlot15 <- DotPlot(linhagens, features = lista_CIFS$V1[90:95], idents = linhagens_sample$value[70:74])
DotPlot16<- DotPlot(linhagens, features = lista_CIFS$V1[96:102], idents = linhagens_sample$value[70:74])

ggsave('Imagens/DotPlot.tiff', plot = DotPlot, width = 10, height = 15)
ggsave('Imagens/DotPlot1.tiff', plot = DotPlot1, width = 10, height = 15)
ggsave('Imagens/DotPlot2.tiff', plot = DotPlot2, width = 10, height = 15)
ggsave('Imagens/DotPlot3.tiff', plot = DotPlot3, width = 10, height = 15)
ggsave('Imagens/DotPlot4.tiff', plot = DotPlot4, width = 10, height = 15)
ggsave('Imagens/DotPlot5.tiff', plot = DotPlot5, width = 10, height = 15)
ggsave('Imagens/DotPlot6.tiff', plot = DotPlot6, width = 10, height = 15)
ggsave('Imagens/DotPlot7.tiff', plot = DotPlot7, width = 10, height = 15)
ggsave('Imagens/DotPlot8.tiff', plot = DotPlot8, width = 10, height = 15)
ggsave('Imagens/DotPlot9.tiff', plot = DotPlot9, width = 10, height = 15)
ggsave('Imagens/DotPlot10.tiff', plot = DotPlot10, width = 10, height = 15)
ggsave('Imagens/DotPlot11.tiff', plot = DotPlot11, width = 10, height = 15)
ggsave('Imagens/DotPlot12.tiff', plot = DotPlot12, width = 10, height = 15)
ggsave('Imagens/DotPlot13.tiff', plot = DotPlot13, width = 10, height = 15)
ggsave('Imagens/DotPlot14.tiff', plot = DotPlot14, width = 10, height = 15)
ggsave('Imagens/DotPlot15.tiff', plot = DotPlot15, width = 10, height = 15)
ggsave('Imagens/DotPlot16.tiff', plot = DotPlot16, width = 10, height = 15)

# OVARY

DotPlot <- DotPlot(linhagens, features = lista_CIFS$V1[1:6], idents = linhagens_sample$value[75:79])
DotPlot1 <- DotPlot(linhagens, features = lista_CIFS$V1[6:11], idents = linhagens_sample$value[75:79])
DotPlot2 <- DotPlot(linhagens, features = lista_CIFS$V1[12:17], idents = linhagens_sample$value[75:79])
DotPlot3 <- DotPlot(linhagens, features = lista_CIFS$V1[18:23], idents = linhagens_sample$value[75:79])
DotPlot4 <- DotPlot(linhagens, features = lista_CIFS$V1[24:29], idents = linhagens_sample$value[75:79])
DotPlot5 <- DotPlot(linhagens, features = lista_CIFS$V1[30:35], idents = linhagens_sample$value[75:79])
DotPlot6 <- DotPlot(linhagens, features = lista_CIFS$V1[36:41], idents = linhagens_sample$value[75:79])
DotPlot7 <- DotPlot(linhagens, features = lista_CIFS$V1[42:47], idents = linhagens_sample$value[75:79])
DotPlot8 <- DotPlot(linhagens, features = lista_CIFS$V1[48:53], idents = linhagens_sample$value[75:79])
DotPlot9 <- DotPlot(linhagens, features = lista_CIFS$V1[54:59], idents = linhagens_sample$value[75:79])
DotPlot10 <- DotPlot(linhagens, features = lista_CIFS$V1[60:65], idents = linhagens_sample$value[75:79])
DotPlot11 <- DotPlot(linhagens, features = lista_CIFS$V1[66:71], idents = linhagens_sample$value[75:79])
DotPlot12 <- DotPlot(linhagens, features = lista_CIFS$V1[72:77], idents = linhagens_sample$value[75:79])
DotPlot13 <- DotPlot(linhagens, features = lista_CIFS$V1[78:83], idents = linhagens_sample$value[75:79])
DotPlot14 <- DotPlot(linhagens, features = lista_CIFS$V1[84:89], idents = linhagens_sample$value[75:79])
DotPlot15 <- DotPlot(linhagens, features = lista_CIFS$V1[90:95], idents = linhagens_sample$value[75:79])
DotPlot16<- DotPlot(linhagens, features = lista_CIFS$V1[96:102], idents = linhagens_sample$value[75:79])

ggsave('Imagens/DotPlot.tiff', plot = DotPlot, width = 10, height = 15)
ggsave('Imagens/DotPlot1.tiff', plot = DotPlot1, width = 10, height = 15)
ggsave('Imagens/DotPlot2.tiff', plot = DotPlot2, width = 10, height = 15)
ggsave('Imagens/DotPlot3.tiff', plot = DotPlot3, width = 10, height = 15)
ggsave('Imagens/DotPlot4.tiff', plot = DotPlot4, width = 10, height = 15)
ggsave('Imagens/DotPlot5.tiff', plot = DotPlot5, width = 10, height = 15)
ggsave('Imagens/DotPlot6.tiff', plot = DotPlot6, width = 10, height = 15)
ggsave('Imagens/DotPlot7.tiff', plot = DotPlot7, width = 10, height = 15)
ggsave('Imagens/DotPlot8.tiff', plot = DotPlot8, width = 10, height = 15)
ggsave('Imagens/DotPlot9.tiff', plot = DotPlot9, width = 10, height = 15)
ggsave('Imagens/DotPlot10.tiff', plot = DotPlot10, width = 10, height = 15)
ggsave('Imagens/DotPlot11.tiff', plot = DotPlot11, width = 10, height = 15)
ggsave('Imagens/DotPlot12.tiff', plot = DotPlot12, width = 10, height = 15)
ggsave('Imagens/DotPlot13.tiff', plot = DotPlot13, width = 10, height = 15)
ggsave('Imagens/DotPlot14.tiff', plot = DotPlot14, width = 10, height = 15)
ggsave('Imagens/DotPlot15.tiff', plot = DotPlot15, width = 10, height = 15)
ggsave('Imagens/DotPlot16.tiff', plot = DotPlot16, width = 10, height = 15)

# OESOPHAGUS 

DotPlot <- DotPlot(linhagens, features = lista_CIFS$V1[1:6], idents = linhagens_sample$value[80:84])
DotPlot1 <- DotPlot(linhagens, features = lista_CIFS$V1[6:11], idents = linhagens_sample$value[80:84])
DotPlot2 <- DotPlot(linhagens, features = lista_CIFS$V1[12:17], idents = linhagens_sample$value[80:84])
DotPlot3 <- DotPlot(linhagens, features = lista_CIFS$V1[18:23], idents = linhagens_sample$value[80:84])
DotPlot4 <- DotPlot(linhagens, features = lista_CIFS$V1[24:29], idents = linhagens_sample$value[80:84])
DotPlot5 <- DotPlot(linhagens, features = lista_CIFS$V1[30:35], idents = linhagens_sample$value[80:84])
DotPlot6 <- DotPlot(linhagens, features = lista_CIFS$V1[36:41], idents = linhagens_sample$value[80:84])
DotPlot7 <- DotPlot(linhagens, features = lista_CIFS$V1[42:47], idents = linhagens_sample$value[80:84])
DotPlot8 <- DotPlot(linhagens, features = lista_CIFS$V1[48:53], idents = linhagens_sample$value[80:84])
DotPlot9 <- DotPlot(linhagens, features = lista_CIFS$V1[54:59], idents = linhagens_sample$value[80:84])
DotPlot10 <- DotPlot(linhagens, features = lista_CIFS$V1[60:65], idents = linhagens_sample$value[80:84])
DotPlot11 <- DotPlot(linhagens, features = lista_CIFS$V1[66:71], idents = linhagens_sample$value[80:84])
DotPlot12 <- DotPlot(linhagens, features = lista_CIFS$V1[72:77], idents = linhagens_sample$value[80:84])
DotPlot13 <- DotPlot(linhagens, features = lista_CIFS$V1[78:83], idents = linhagens_sample$value[80:84])
DotPlot14 <- DotPlot(linhagens, features = lista_CIFS$V1[84:89], idents = linhagens_sample$value[80:84])
DotPlot15 <- DotPlot(linhagens, features = lista_CIFS$V1[90:95], idents = linhagens_sample$value[80:84])
DotPlot16<- DotPlot(linhagens, features = lista_CIFS$V1[96:102], idents = linhagens_sample$value[80:84])

ggsave('Imagens/DotPlot.tiff', plot = DotPlot, width = 10, height = 15)
ggsave('Imagens/DotPlot1.tiff', plot = DotPlot1, width = 10, height = 15)
ggsave('Imagens/DotPlot2.tiff', plot = DotPlot2, width = 10, height = 15)
ggsave('Imagens/DotPlot3.tiff', plot = DotPlot3, width = 10, height = 15)
ggsave('Imagens/DotPlot4.tiff', plot = DotPlot4, width = 10, height = 15)
ggsave('Imagens/DotPlot5.tiff', plot = DotPlot5, width = 10, height = 15)
ggsave('Imagens/DotPlot6.tiff', plot = DotPlot6, width = 10, height = 15)
ggsave('Imagens/DotPlot7.tiff', plot = DotPlot7, width = 10, height = 15)
ggsave('Imagens/DotPlot8.tiff', plot = DotPlot8, width = 10, height = 15)
ggsave('Imagens/DotPlot9.tiff', plot = DotPlot9, width = 10, height = 15)
ggsave('Imagens/DotPlot10.tiff', plot = DotPlot10, width = 10, height = 15)
ggsave('Imagens/DotPlot11.tiff', plot = DotPlot11, width = 10, height = 15)
ggsave('Imagens/DotPlot12.tiff', plot = DotPlot12, width = 10, height = 15)
ggsave('Imagens/DotPlot13.tiff', plot = DotPlot13, width = 10, height = 15)
ggsave('Imagens/DotPlot14.tiff', plot = DotPlot14, width = 10, height = 15)
ggsave('Imagens/DotPlot15.tiff', plot = DotPlot15, width = 10, height = 15)
ggsave('Imagens/DotPlot16.tiff', plot = DotPlot16, width = 10, height = 15)