library(Seurat)
library(patchwork)
library(tidyverse)
library(cowplot)
library(data.table)
library(Matrix)
library(dplyr)
library(readxl)
library(wrapr)

setwd("~/Library/CloudStorage/GoogleDrive-caio.mussatto@unesp.br/Meu Drive/Projeto_de_Pesquisa /DATA")

# Lendo os arquivos

linhagens <- readRDS('linhagens.rds')
lista_CIFS <- read.table('CIFS_filtrada.txt')

#linhagens_sample <- as_tibble(linhagens$sample)

#linhagens_sample <- distinct(linhagens_sample)

#write_csv(linhagens_sample, 'linhagens_sample.csv')

linhagens_sample <- read_csv('linhagens_sample.csv')


# THYROID

VlnPlot1 <- VlnPlot(linhagens, features = lista_CIFS$V1[1:12], idents = linhagens_sample$value[1:4])
VlnPlot2 <- VlnPlot(linhagens, features = lista_CIFS$V1[13:24], idents = linhagens_sample$value[1:4])
VlnPlot3 <- VlnPlot(linhagens, features = lista_CIFS$V1[25:36], idents = linhagens_sample$value[1:4])
VlnPlot4 <- VlnPlot(linhagens, features = lista_CIFS$V1[37:48], idents = linhagens_sample$value[1:4])
VlnPlot5 <- VlnPlot(linhagens, features = lista_CIFS$V1[49:60], idents = linhagens_sample$value[1:4])
VlnPlot6 <- VlnPlot(linhagens, features = lista_CIFS$V1[61:72], idents = linhagens_sample$value[1:4])
VlnPlot7 <- VlnPlot(linhagens, features = lista_CIFS$V1[73:84], idents = linhagens_sample$value[1:4])
VlnPlot8 <- VlnPlot(linhagens, features = lista_CIFS$V1[85:96], idents = linhagens_sample$value[1:4])
VlnPlot9 <- VlnPlot(linhagens, features = lista_CIFS$V1[97:102], idents = linhagens_sample$value[1:4])

ggsave('Imagens/VLnPLot1.tiff', plot = VlnPlot1, width = 10, height = 10)
ggsave('Imagens/VlnPlot2.tiff', plot = VlnPlot2, width = 10, height = 10)
ggsave('Imagens/VlnPlot3.tiff', plot = VlnPlot3, width = 10, height = 10)
ggsave('Imagens/VlnPlot4.tiff', plot = VlnPlot4, width = 10, height = 10)
ggsave('Imagens/VlnPlot5.tiff', plot = VlnPlot5, width = 10, height = 10)
ggsave('Imagens/VlnPlot6.tiff', plot = VlnPlot6, width = 10, height = 10)
ggsave('Imagens/VlnPlot7.tiff', plot = VlnPlot7, width = 10, height = 10)
ggsave('Imagens/VlnPlot8.tiff', plot = VlnPlot8, width = 10, height = 10)
ggsave('Imagens/VlnPlot9.tiff', plot = VlnPlot9, width = 10, height = 10)

# ENDOMETRIUM

VlnPlot1 <- VlnPlot(linhagens, features = lista_CIFS$V1[1:12], idents = linhagens_sample$value[5:9])
VlnPlot2 <- VlnPlot(linhagens, features = lista_CIFS$V1[13:24], idents = linhagens_sample$value[5:9])
VlnPlot3 <- VlnPlot(linhagens, features = lista_CIFS$V1[25:36], idents = linhagens_sample$value[5:9])
VlnPlot4 <- VlnPlot(linhagens, features = lista_CIFS$V1[37:48], idents = linhagens_sample$value[5:9])
VlnPlot5 <- VlnPlot(linhagens, features = lista_CIFS$V1[49:60], idents = linhagens_sample$value[5:9])
VlnPlot6 <- VlnPlot(linhagens, features = lista_CIFS$V1[61:72], idents = linhagens_sample$value[5:9])
VlnPlot7 <- VlnPlot(linhagens, features = lista_CIFS$V1[73:84], idents = linhagens_sample$value[5:9])
VlnPlot8 <- VlnPlot(linhagens, features = lista_CIFS$V1[85:96], idents = linhagens_sample$value[5:9])
VlnPlot9 <- VlnPlot(linhagens, features = lista_CIFS$V1[97:102], idents = linhagens_sample$value[5:9])

ggsave('Imagens/VLnPLot1.tiff', plot = VlnPlot1, width = 10, height = 10)
ggsave('Imagens/VlnPlot2.tiff', plot = VlnPlot2, width = 10, height = 10)
ggsave('Imagens/VlnPlot3.tiff', plot = VlnPlot3, width = 10, height = 10)
ggsave('Imagens/VlnPlot4.tiff', plot = VlnPlot4, width = 10, height = 10)
ggsave('Imagens/VlnPlot5.tiff', plot = VlnPlot5, width = 10, height = 10)
ggsave('Imagens/VlnPlot6.tiff', plot = VlnPlot6, width = 10, height = 10)
ggsave('Imagens/VlnPlot7.tiff', plot = VlnPlot7, width = 10, height = 10)
ggsave('Imagens/VlnPlot8.tiff', plot = VlnPlot8, width = 10, height = 10)
ggsave('Imagens/VlnPlot9.tiff', plot = VlnPlot9, width = 10, height = 10)

# SKIN

VlnPlot1 <- VlnPlot(linhagens, features = lista_CIFS$V1[1:12], idents = linhagens_sample$value[10:14])
VlnPlot2 <- VlnPlot(linhagens, features = lista_CIFS$V1[13:24], idents = linhagens_sample$value[10:14])
VlnPlot3 <- VlnPlot(linhagens, features = lista_CIFS$V1[25:36], idents = linhagens_sample$value[10:14])
VlnPlot4 <- VlnPlot(linhagens, features = lista_CIFS$V1[37:48], idents = linhagens_sample$value[10:14])
VlnPlot5 <- VlnPlot(linhagens, features = lista_CIFS$V1[49:60], idents = linhagens_sample$value[10:14])
VlnPlot6 <- VlnPlot(linhagens, features = lista_CIFS$V1[61:72], idents = linhagens_sample$value[10:14])
VlnPlot7 <- VlnPlot(linhagens, features = lista_CIFS$V1[73:84], idents = linhagens_sample$value[10:14])
VlnPlot8 <- VlnPlot(linhagens, features = lista_CIFS$V1[85:96], idents = linhagens_sample$value[10:14])
VlnPlot9 <- VlnPlot(linhagens, features = lista_CIFS$V1[97:102], idents = linhagens_sample$value[10:14])

ggsave('Imagens/VLnPLot1.tiff', plot = VlnPlot1, width = 10, height = 10)
ggsave('Imagens/VlnPlot2.tiff', plot = VlnPlot2, width = 10, height = 10)
ggsave('Imagens/VlnPlot3.tiff', plot = VlnPlot3, width = 10, height = 10)
ggsave('Imagens/VlnPlot4.tiff', plot = VlnPlot4, width = 10, height = 10)
ggsave('Imagens/VlnPlot5.tiff', plot = VlnPlot5, width = 10, height = 10)
ggsave('Imagens/VlnPlot6.tiff', plot = VlnPlot6, width = 10, height = 10)
ggsave('Imagens/VlnPlot7.tiff', plot = VlnPlot7, width = 10, height = 10)
ggsave('Imagens/VlnPlot8.tiff', plot = VlnPlot8, width = 10, height = 10)
ggsave('Imagens/VlnPlot9.tiff', plot = VlnPlot9, width = 10, height = 10)

# LIVER

VlnPlot1 <- VlnPlot(linhagens, features = lista_CIFS$V1[1:12], idents = linhagens_sample$value[15:19])
VlnPlot2 <- VlnPlot(linhagens, features = lista_CIFS$V1[13:24], idents = linhagens_sample$value[15:19])
VlnPlot3 <- VlnPlot(linhagens, features = lista_CIFS$V1[25:36], idents = linhagens_sample$value[15:19])
VlnPlot4 <- VlnPlot(linhagens, features = lista_CIFS$V1[37:48], idents = linhagens_sample$value[15:19])
VlnPlot5 <- VlnPlot(linhagens, features = lista_CIFS$V1[49:60], idents = linhagens_sample$value[15:19])
VlnPlot6 <- VlnPlot(linhagens, features = lista_CIFS$V1[61:72], idents = linhagens_sample$value[15:19])
VlnPlot7 <- VlnPlot(linhagens, features = lista_CIFS$V1[73:84], idents = linhagens_sample$value[15:19])
VlnPlot8 <- VlnPlot(linhagens, features = lista_CIFS$V1[85:96], idents = linhagens_sample$value[15:19])
VlnPlot9 <- VlnPlot(linhagens, features = lista_CIFS$V1[97:102], idents = linhagens_sample$value[15:19])

ggsave('Imagens/VLnPLot1.tiff', plot = VlnPlot1, width = 10, height = 10)
ggsave('Imagens/VlnPlot2.tiff', plot = VlnPlot2, width = 10, height = 10)
ggsave('Imagens/VlnPlot3.tiff', plot = VlnPlot3, width = 10, height = 10)
ggsave('Imagens/VlnPlot4.tiff', plot = VlnPlot4, width = 10, height = 10)
ggsave('Imagens/VlnPlot5.tiff', plot = VlnPlot5, width = 10, height = 10)
ggsave('Imagens/VlnPlot6.tiff', plot = VlnPlot6, width = 10, height = 10)
ggsave('Imagens/VlnPlot7.tiff', plot = VlnPlot7, width = 10, height = 10)
ggsave('Imagens/VlnPlot8.tiff', plot = VlnPlot8, width = 10, height = 10)
ggsave('Imagens/VlnPlot9.tiff', plot = VlnPlot9, width = 10, height = 10)

# CENTRAL_NERVOUS_SYSTEM - ver dnv dps

VlnPlot <- VlnPlot(linhagens, features = lista_CIFS$V1[1:6], idents = linhagens_sample$value[20:24])
VlnPlot1 <- VlnPlot(linhagens, features = lista_CIFS$V1[6:11], idents = linhagens_sample$value[20:24])
VlnPlot2 <- VlnPlot(linhagens, features = lista_CIFS$V1[12:17], idents = linhagens_sample$value[20:24])
VlnPlot3 <- VlnPlot(linhagens, features = lista_CIFS$V1[18:23], idents = linhagens_sample$value[20:24])
VlnPlot4 <- VlnPlot(linhagens, features = lista_CIFS$V1[24:29], idents = linhagens_sample$value[20:24])
VlnPlot5 <- VlnPlot(linhagens, features = lista_CIFS$V1[30:35], idents = linhagens_sample$value[20:24])
VlnPlot6 <- VlnPlot(linhagens, features = lista_CIFS$V1[36:41], idents = linhagens_sample$value[20:24])
VlnPlot7 <- VlnPlot(linhagens, features = lista_CIFS$V1[42:47], idents = linhagens_sample$value[20:24])
VlnPlot8 <- VlnPlot(linhagens, features = lista_CIFS$V1[48:53], idents = linhagens_sample$value[20:24])
VlnPlot9 <- VlnPlot(linhagens, features = lista_CIFS$V1[54:59], idents = linhagens_sample$value[20:24])
VlnPlot10 <- VlnPlot(linhagens, features = lista_CIFS$V1[60:65], idents = linhagens_sample$value[20:24])
VlnPlot11 <- VlnPlot(linhagens, features = lista_CIFS$V1[66:71], idents = linhagens_sample$value[20:24])
VlnPlot12 <- VlnPlot(linhagens, features = lista_CIFS$V1[72:77], idents = linhagens_sample$value[20:24])
VlnPlot13 <- VlnPlot(linhagens, features = lista_CIFS$V1[78:83], idents = linhagens_sample$value[20:24])
VlnPlot14 <- VlnPlot(linhagens, features = lista_CIFS$V1[84:89], idents = linhagens_sample$value[20:24])
VlnPlot15 <- VlnPlot(linhagens, features = lista_CIFS$V1[90:95], idents = linhagens_sample$value[20:24])
VlnPlot16<- VlnPlot(linhagens, features = lista_CIFS$V1[96:101], idents = linhagens_sample$value[20:24])
VlnPlot17 <- VlnPlot(linhagens, features = lista_CIFS$V1[102], idents = linhagens_sample$value[20:24])

ggsave('Imagens/VlnPlot.tiff', plot = VlnPlot, width = 10, height = 10)
ggsave('Imagens/VlnPlot1.tiff', plot = VlnPlot1, width = 10, height = 10)
ggsave('Imagens/VlnPlot2.tiff', plot = VlnPlot2, width = 10, height = 10)
ggsave('Imagens/VlnPlot3.tiff', plot = VlnPlot3, width = 10, height = 10)
ggsave('Imagens/VlnPlot4.tiff', plot = VlnPlot4, width = 10, height = 10)
ggsave('Imagens/VlnPlot5.tiff', plot = VlnPlot5, width = 10, height = 10)
ggsave('Imagens/VlnPlot6.tiff', plot = VlnPlot6, width = 10, height = 10)
ggsave('Imagens/VlnPlot7.tiff', plot = VlnPlot7, width = 10, height = 10)
ggsave('Imagens/VlnPlot8.tiff', plot = VlnPlot8, width = 10, height = 10)
ggsave('Imagens/VlnPlot9.tiff', plot = VlnPlot9, width = 10, height = 10)
ggsave('Imagens/VlnPlot10.tiff', plot = VlnPlot10, width = 10, height = 10)
ggsave('Imagens/VlnPlot11.tiff', plot = VlnPlot11, width = 10, height = 10)
ggsave('Imagens/VlnPlot12.tiff', plot = VlnPlot12, width = 10, height = 10)
ggsave('Imagens/VlnPlot13.tiff', plot = VlnPlot13, width = 10, height = 10)
ggsave('Imagens/VlnPlot14.tiff', plot = VlnPlot14, width = 10, height = 10)
ggsave('Imagens/VlnPlot15.tiff', plot = VlnPlot15, width = 10, height = 10)
ggsave('Imagens/VlnPlot16.tiff', plot = VlnPlot16, width = 10, height = 10)
ggsave('Imagens/VlnPlot17.tiff', plot = VlnPlot17, width = 10, height = 10)


# URINARY_TRACT

VlnPlot1 <- VlnPlot(linhagens, features = lista_CIFS$V1[1:12], idents = linhagens_sample$value[25:29])
VlnPlot2 <- VlnPlot(linhagens, features = lista_CIFS$V1[13:24], idents = linhagens_sample$value[25:29])
VlnPlot3 <- VlnPlot(linhagens, features = lista_CIFS$V1[25:36], idents = linhagens_sample$value[25:29])
VlnPlot4 <- VlnPlot(linhagens, features = lista_CIFS$V1[37:48], idents = linhagens_sample$value[25:29])
VlnPlot5 <- VlnPlot(linhagens, features = lista_CIFS$V1[49:60], idents = linhagens_sample$value[25:29])
VlnPlot6 <- VlnPlot(linhagens, features = lista_CIFS$V1[61:72], idents = linhagens_sample$value[25:29])
VlnPlot7 <- VlnPlot(linhagens, features = lista_CIFS$V1[73:84], idents = linhagens_sample$value[25:29])
VlnPlot8 <- VlnPlot(linhagens, features = lista_CIFS$V1[85:96], idents = linhagens_sample$value[25:29])
VlnPlot9 <- VlnPlot(linhagens, features = lista_CIFS$V1[97:102], idents = linhagens_sample$value[25:29])

ggsave('Imagens/VLnPLot1.tiff', plot = VlnPlot1, width = 10, height = 10)
ggsave('Imagens/VlnPlot2.tiff', plot = VlnPlot2, width = 10, height = 10)
ggsave('Imagens/VlnPlot3.tiff', plot = VlnPlot3, width = 10, height = 10)
ggsave('Imagens/VlnPlot4.tiff', plot = VlnPlot4, width = 10, height = 10)
ggsave('Imagens/VlnPlot5.tiff', plot = VlnPlot5, width = 10, height = 10)
ggsave('Imagens/VlnPlot6.tiff', plot = VlnPlot6, width = 10, height = 10)
ggsave('Imagens/VlnPlot7.tiff', plot = VlnPlot7, width = 10, height = 10)
ggsave('Imagens/VlnPlot8.tiff', plot = VlnPlot8, width = 10, height = 10)
ggsave('Imagens/VlnPlot9.tiff', plot = VlnPlot9, width = 10, height = 10)

# BILIARY_TRACT

VlnPlot1 <- VlnPlot(linhagens, features = lista_CIFS$V1[1:12], idents = linhagens_sample$value[30:34])
VlnPlot2 <- VlnPlot(linhagens, features = lista_CIFS$V1[13:24], idents = linhagens_sample$value[30:34])
VlnPlot3 <- VlnPlot(linhagens, features = lista_CIFS$V1[25:36], idents = linhagens_sample$value[30:34])
VlnPlot4 <- VlnPlot(linhagens, features = lista_CIFS$V1[37:48], idents = linhagens_sample$value[30:34])
VlnPlot5 <- VlnPlot(linhagens, features = lista_CIFS$V1[49:60], idents = linhagens_sample$value[30:34])
VlnPlot6 <- VlnPlot(linhagens, features = lista_CIFS$V1[61:72], idents = linhagens_sample$value[30:34])
VlnPlot7 <- VlnPlot(linhagens, features = lista_CIFS$V1[73:84], idents = linhagens_sample$value[30:34])
VlnPlot8 <- VlnPlot(linhagens, features = lista_CIFS$V1[85:96], idents = linhagens_sample$value[30:34])
VlnPlot9 <- VlnPlot(linhagens, features = lista_CIFS$V1[97:102], idents = linhagens_sample$value[30:34])

ggsave('Imagens/VLnPLot1.tiff', plot = VlnPlot1, width = 10, height = 10)
ggsave('Imagens/VlnPlot2.tiff', plot = VlnPlot2, width = 10, height = 10)
ggsave('Imagens/VlnPlot3.tiff', plot = VlnPlot3, width = 10, height = 10)
ggsave('Imagens/VlnPlot4.tiff', plot = VlnPlot4, width = 10, height = 10)
ggsave('Imagens/VlnPlot5.tiff', plot = VlnPlot5, width = 10, height = 10)
ggsave('Imagens/VlnPlot6.tiff', plot = VlnPlot6, width = 10, height = 10)
ggsave('Imagens/VlnPlot7.tiff', plot = VlnPlot7, width = 10, height = 10)
ggsave('Imagens/VlnPlot8.tiff', plot = VlnPlot8, width = 10, height = 10)
ggsave('Imagens/VlnPlot9.tiff', plot = VlnPlot9, width = 10, height = 10)

# BREAST

VlnPlot1 <- VlnPlot(linhagens, features = lista_CIFS$V1[1:12], idents = linhagens_sample$value[35:39])
VlnPlot2 <- VlnPlot(linhagens, features = lista_CIFS$V1[13:24], idents = linhagens_sample$value[35:39])
VlnPlot3 <- VlnPlot(linhagens, features = lista_CIFS$V1[25:36], idents = linhagens_sample$value[35:39])
VlnPlot4 <- VlnPlot(linhagens, features = lista_CIFS$V1[37:48], idents = linhagens_sample$value[35:39])
VlnPlot5 <- VlnPlot(linhagens, features = lista_CIFS$V1[49:60], idents = linhagens_sample$value[35:39])
VlnPlot6 <- VlnPlot(linhagens, features = lista_CIFS$V1[61:72], idents = linhagens_sample$value[35:39])
VlnPlot7 <- VlnPlot(linhagens, features = lista_CIFS$V1[73:84], idents = linhagens_sample$value[35:39])
VlnPlot8 <- VlnPlot(linhagens, features = lista_CIFS$V1[85:96], idents = linhagens_sample$value[35:39])
VlnPlot9 <- VlnPlot(linhagens, features = lista_CIFS$V1[97:102], idents = linhagens_sample$value[35:39])

ggsave('Imagens/VLnPLot1.tiff', plot = VlnPlot1, width = 10, height = 10)
ggsave('Imagens/VlnPlot2.tiff', plot = VlnPlot2, width = 10, height = 10)
ggsave('Imagens/VlnPlot3.tiff', plot = VlnPlot3, width = 10, height = 10)
ggsave('Imagens/VlnPlot4.tiff', plot = VlnPlot4, width = 10, height = 10)
ggsave('Imagens/VlnPlot5.tiff', plot = VlnPlot5, width = 10, height = 10)
ggsave('Imagens/VlnPlot6.tiff', plot = VlnPlot6, width = 10, height = 10)
ggsave('Imagens/VlnPlot7.tiff', plot = VlnPlot7, width = 10, height = 10)
ggsave('Imagens/VlnPlot8.tiff', plot = VlnPlot8, width = 10, height = 10)
ggsave('Imagens/VlnPlot9.tiff', plot = VlnPlot9, width = 10, height = 10)


# UPPER_AERODIGESTIVE_TRACT - ver dnv dps

VlnPlot <- VlnPlot(linhagens, features = lista_CIFS$V1[1:6], idents = linhagens_sample$value[40:44])
VlnPlot1 <- VlnPlot(linhagens, features = lista_CIFS$V1[6:11], idents = linhagens_sample$value[40:44])
VlnPlot2 <- VlnPlot(linhagens, features = lista_CIFS$V1[12:17], idents = linhagens_sample$value[40:44])
VlnPlot3 <- VlnPlot(linhagens, features = lista_CIFS$V1[18:23], idents = linhagens_sample$value[40:44])
VlnPlot4 <- VlnPlot(linhagens, features = lista_CIFS$V1[24:29], idents = linhagens_sample$value[40:44])
VlnPlot5 <- VlnPlot(linhagens, features = lista_CIFS$V1[30:35], idents = linhagens_sample$value[40:44])
VlnPlot6 <- VlnPlot(linhagens, features = lista_CIFS$V1[36:41], idents = linhagens_sample$value[40:44])
VlnPlot7 <- VlnPlot(linhagens, features = lista_CIFS$V1[42:47], idents = linhagens_sample$value[40:44])
VlnPlot8 <- VlnPlot(linhagens, features = lista_CIFS$V1[48:53], idents = linhagens_sample$value[40:44])
VlnPlot9 <- VlnPlot(linhagens, features = lista_CIFS$V1[54:59], idents = linhagens_sample$value[40:44])
VlnPlot10 <- VlnPlot(linhagens, features = lista_CIFS$V1[60:65], idents = linhagens_sample$value[40:44])
VlnPlot11 <- VlnPlot(linhagens, features = lista_CIFS$V1[66:71], idents = linhagens_sample$value[40:44])
VlnPlot12 <- VlnPlot(linhagens, features = lista_CIFS$V1[72:77], idents = linhagens_sample$value[40:44])
VlnPlot13 <- VlnPlot(linhagens, features = lista_CIFS$V1[78:83], idents = linhagens_sample$value[40:44])
VlnPlot14 <- VlnPlot(linhagens, features = lista_CIFS$V1[84:89], idents = linhagens_sample$value[40:44])
VlnPlot15 <- VlnPlot(linhagens, features = lista_CIFS$V1[90:95], idents = linhagens_sample$value[40:44])
VlnPlot16<- VlnPlot(linhagens, features = lista_CIFS$V1[96:101], idents = linhagens_sample$value[40:44])
VlnPlot17 <- VlnPlot(linhagens, features = lista_CIFS$V1[102], idents = linhagens_sample$value[40:44])

ggsave('Imagens/VlnPlot.tiff', plot = VlnPlot, width = 10, height = 10)
ggsave('Imagens/VlnPlot1.tiff', plot = VlnPlot1, width = 10, height = 10)
ggsave('Imagens/VlnPlot2.tiff', plot = VlnPlot2, width = 10, height = 10)
ggsave('Imagens/VlnPlot3.tiff', plot = VlnPlot3, width = 10, height = 10)
ggsave('Imagens/VlnPlot4.tiff', plot = VlnPlot4, width = 10, height = 10)
ggsave('Imagens/VlnPlot5.tiff', plot = VlnPlot5, width = 10, height = 10)
ggsave('Imagens/VlnPlot6.tiff', plot = VlnPlot6, width = 10, height = 10)
ggsave('Imagens/VlnPlot7.tiff', plot = VlnPlot7, width = 10, height = 10)
ggsave('Imagens/VlnPlot8.tiff', plot = VlnPlot8, width = 10, height = 10)
ggsave('Imagens/VlnPlot9.tiff', plot = VlnPlot9, width = 10, height = 10)
ggsave('Imagens/VlnPlot10.tiff', plot = VlnPlot10, width = 10, height = 10)
ggsave('Imagens/VlnPlot11.tiff', plot = VlnPlot11, width = 10, height = 10)
ggsave('Imagens/VlnPlot12.tiff', plot = VlnPlot12, width = 10, height = 10)
ggsave('Imagens/VlnPlot13.tiff', plot = VlnPlot13, width = 10, height = 10)
ggsave('Imagens/VlnPlot14.tiff', plot = VlnPlot14, width = 10, height = 10)
ggsave('Imagens/VlnPlot15.tiff', plot = VlnPlot15, width = 10, height = 10)
ggsave('Imagens/VlnPlot16.tiff', plot = VlnPlot16, width = 10, height = 10)
ggsave('Imagens/VlnPlot17.tiff', plot = VlnPlot17, width = 10, height = 10)

# STOMACH

VlnPlot1 <- VlnPlot(linhagens, features = lista_CIFS$V1[1:12], idents = linhagens_sample$value[45:49])
VlnPlot2 <- VlnPlot(linhagens, features = lista_CIFS$V1[13:24], idents = linhagens_sample$value[45:49])
VlnPlot3 <- VlnPlot(linhagens, features = lista_CIFS$V1[25:36], idents = linhagens_sample$value[45:49])
VlnPlot4 <- VlnPlot(linhagens, features = lista_CIFS$V1[37:48], idents = linhagens_sample$value[45:49])
VlnPlot5 <- VlnPlot(linhagens, features = lista_CIFS$V1[49:60], idents = linhagens_sample$value[45:49])
VlnPlot6 <- VlnPlot(linhagens, features = lista_CIFS$V1[61:72], idents = linhagens_sample$value[45:49])
VlnPlot7 <- VlnPlot(linhagens, features = lista_CIFS$V1[73:84], idents = linhagens_sample$value[45:49])
VlnPlot8 <- VlnPlot(linhagens, features = lista_CIFS$V1[85:96], idents = linhagens_sample$value[45:49])
VlnPlot9 <- VlnPlot(linhagens, features = lista_CIFS$V1[97:102], idents = linhagens_sample$value[45:49])

ggsave('Imagens/VLnPLot1.tiff', plot = VlnPlot1, width = 10, height = 10)
ggsave('Imagens/VlnPlot2.tiff', plot = VlnPlot2, width = 10, height = 10)
ggsave('Imagens/VlnPlot3.tiff', plot = VlnPlot3, width = 10, height = 10)
ggsave('Imagens/VlnPlot4.tiff', plot = VlnPlot4, width = 10, height = 10)
ggsave('Imagens/VlnPlot5.tiff', plot = VlnPlot5, width = 10, height = 10)
ggsave('Imagens/VlnPlot6.tiff', plot = VlnPlot6, width = 10, height = 10)
ggsave('Imagens/VlnPlot7.tiff', plot = VlnPlot7, width = 10, height = 10)
ggsave('Imagens/VlnPlot8.tiff', plot = VlnPlot8, width = 10, height = 10)
ggsave('Imagens/VlnPlot9.tiff', plot = VlnPlot9, width = 10, height = 10)

# LARGE_INSTETINE

VlnPlot1 <- VlnPlot(linhagens, features = lista_CIFS$V1[1:12], idents = linhagens_sample$value[50:54])
VlnPlot2 <- VlnPlot(linhagens, features = lista_CIFS$V1[13:24], idents = linhagens_sample$value[50:54])
VlnPlot3 <- VlnPlot(linhagens, features = lista_CIFS$V1[25:36], idents = linhagens_sample$value[50:54])
VlnPlot4 <- VlnPlot(linhagens, features = lista_CIFS$V1[37:48], idents = linhagens_sample$value[50:54])
VlnPlot5 <- VlnPlot(linhagens, features = lista_CIFS$V1[49:60], idents = linhagens_sample$value[50:54])
VlnPlot6 <- VlnPlot(linhagens, features = lista_CIFS$V1[61:72], idents = linhagens_sample$value[50:54])
VlnPlot7 <- VlnPlot(linhagens, features = lista_CIFS$V1[73:84], idents = linhagens_sample$value[50:54])
VlnPlot8 <- VlnPlot(linhagens, features = lista_CIFS$V1[85:96], idents = linhagens_sample$value[50:54])
VlnPlot9 <- VlnPlot(linhagens, features = lista_CIFS$V1[97:102], idents = linhagens_sample$value[50:54])

ggsave('Imagens/VLnPLot1.tiff', plot = VlnPlot1, width = 10, height = 10)
ggsave('Imagens/VlnPlot2.tiff', plot = VlnPlot2, width = 10, height = 10)
ggsave('Imagens/VlnPlot3.tiff', plot = VlnPlot3, width = 10, height = 10)
ggsave('Imagens/VlnPlot4.tiff', plot = VlnPlot4, width = 10, height = 10)
ggsave('Imagens/VlnPlot5.tiff', plot = VlnPlot5, width = 10, height = 10)
ggsave('Imagens/VlnPlot6.tiff', plot = VlnPlot6, width = 10, height = 10)
ggsave('Imagens/VlnPlot7.tiff', plot = VlnPlot7, width = 10, height = 10)
ggsave('Imagens/VlnPlot8.tiff', plot = VlnPlot8, width = 10, height = 10)
ggsave('Imagens/VlnPlot9.tiff', plot = VlnPlot9, width = 10, height = 10)

# PROSTATE - ver dnv dps
VlnPlot <- VlnPlot(linhagens, features = lista_CIFS$V1[1:6], idents = linhagens_sample$value[55:56])
VlnPlot1 <- VlnPlot(linhagens, features = lista_CIFS$V1[6:11], idents = linhagens_sample$value[55:56])
VlnPlot2 <- VlnPlot(linhagens, features = lista_CIFS$V1[12:17], idents = linhagens_sample$value[55:56])
VlnPlot3 <- VlnPlot(linhagens, features = lista_CIFS$V1[18:23], idents = linhagens_sample$value[55:56])
VlnPlot4 <- VlnPlot(linhagens, features = lista_CIFS$V1[24:29], idents = linhagens_sample$value[55:56])
VlnPlot5 <- VlnPlot(linhagens, features = lista_CIFS$V1[30:35], idents = linhagens_sample$value[55:56])
VlnPlot6 <- VlnPlot(linhagens, features = lista_CIFS$V1[36:41], idents = linhagens_sample$value[55:56])
VlnPlot7 <- VlnPlot(linhagens, features = lista_CIFS$V1[42:47], idents = linhagens_sample$value[55:56])
VlnPlot8 <- VlnPlot(linhagens, features = lista_CIFS$V1[48:53], idents = linhagens_sample$value[55:56])
VlnPlot9 <- VlnPlot(linhagens, features = lista_CIFS$V1[54:59], idents = linhagens_sample$value[55:56])
VlnPlot10 <- VlnPlot(linhagens, features = lista_CIFS$V1[60:65], idents = linhagens_sample$value[55:56])
VlnPlot11 <- VlnPlot(linhagens, features = lista_CIFS$V1[66:71], idents = linhagens_sample$value[55:56])
VlnPlot12 <- VlnPlot(linhagens, features = lista_CIFS$V1[72:77], idents = linhagens_sample$value[55:56])
VlnPlot13 <- VlnPlot(linhagens, features = lista_CIFS$V1[78:83], idents = linhagens_sample$value[55:56])
VlnPlot14 <- VlnPlot(linhagens, features = lista_CIFS$V1[84:89], idents = linhagens_sample$value[55:56])
VlnPlot15 <- VlnPlot(linhagens, features = lista_CIFS$V1[90:95], idents = linhagens_sample$value[55:56])
VlnPlot16<- VlnPlot(linhagens, features = lista_CIFS$V1[96:101], idents = linhagens_sample$value[55:56])
VlnPlot17 <- VlnPlot(linhagens, features = lista_CIFS$V1[102], idents = linhagens_sample$value[55:56])

ggsave('Imagens/VlnPlot.tiff', plot = VlnPlot, width = 10, height = 10)
ggsave('Imagens/VlnPlot1.tiff', plot = VlnPlot1, width = 10, height = 10)
ggsave('Imagens/VlnPlot2.tiff', plot = VlnPlot2, width = 10, height = 10)
ggsave('Imagens/VlnPlot3.tiff', plot = VlnPlot3, width = 10, height = 10)
ggsave('Imagens/VlnPlot4.tiff', plot = VlnPlot4, width = 10, height = 10)
ggsave('Imagens/VlnPlot5.tiff', plot = VlnPlot5, width = 10, height = 10)
ggsave('Imagens/VlnPlot6.tiff', plot = VlnPlot6, width = 10, height = 10)
ggsave('Imagens/VlnPlot7.tiff', plot = VlnPlot7, width = 10, height = 10)
ggsave('Imagens/VlnPlot8.tiff', plot = VlnPlot8, width = 10, height = 10)
ggsave('Imagens/VlnPlot9.tiff', plot = VlnPlot9, width = 10, height = 10)
ggsave('Imagens/VlnPlot10.tiff', plot = VlnPlot10, width = 10, height = 10)
ggsave('Imagens/VlnPlot11.tiff', plot = VlnPlot11, width = 10, height = 10)
ggsave('Imagens/VlnPlot12.tiff', plot = VlnPlot12, width = 10, height = 10)
ggsave('Imagens/VlnPlot13.tiff', plot = VlnPlot13, width = 10, height = 10)
ggsave('Imagens/VlnPlot14.tiff', plot = VlnPlot14, width = 10, height = 10)
ggsave('Imagens/VlnPlot15.tiff', plot = VlnPlot15, width = 10, height = 10)
ggsave('Imagens/VlnPlot16.tiff', plot = VlnPlot16, width = 10, height = 10)
ggsave('Imagens/VlnPlot17.tiff', plot = VlnPlot17, width = 10, height = 10)

# KIDNEY

VlnPlot1 <- VlnPlot(linhagens, features = lista_CIFS$V1[1:12], idents = linhagens_sample$value[57:61])
VlnPlot2 <- VlnPlot(linhagens, features = lista_CIFS$V1[13:24], idents = linhagens_sample$value[57:61])
VlnPlot3 <- VlnPlot(linhagens, features = lista_CIFS$V1[25:36], idents = linhagens_sample$value[57:61])
VlnPlot4 <- VlnPlot(linhagens, features = lista_CIFS$V1[37:48], idents = linhagens_sample$value[57:61])
VlnPlot5 <- VlnPlot(linhagens, features = lista_CIFS$V1[49:60], idents = linhagens_sample$value[57:61])
VlnPlot6 <- VlnPlot(linhagens, features = lista_CIFS$V1[61:72], idents = linhagens_sample$value[57:61])
VlnPlot7 <- VlnPlot(linhagens, features = lista_CIFS$V1[73:84], idents = linhagens_sample$value[57:61])
VlnPlot8 <- VlnPlot(linhagens, features = lista_CIFS$V1[85:96], idents = linhagens_sample$value[57:61])
VlnPlot9 <- VlnPlot(linhagens, features = lista_CIFS$V1[97:102], idents = linhagens_sample$value[57:61])

ggsave('Imagens/VLnPLot1.tiff', plot = VlnPlot1, width = 10, height = 10)
ggsave('Imagens/VlnPlot2.tiff', plot = VlnPlot2, width = 10, height = 10)
ggsave('Imagens/VlnPlot3.tiff', plot = VlnPlot3, width = 10, height = 10)
ggsave('Imagens/VlnPlot4.tiff', plot = VlnPlot4, width = 10, height = 10)
ggsave('Imagens/VlnPlot5.tiff', plot = VlnPlot5, width = 10, height = 10)
ggsave('Imagens/VlnPlot6.tiff', plot = VlnPlot6, width = 10, height = 10)
ggsave('Imagens/VlnPlot7.tiff', plot = VlnPlot7, width = 10, height = 10)
ggsave('Imagens/VlnPlot8.tiff', plot = VlnPlot8, width = 10, height = 10)
ggsave('Imagens/VlnPlot9.tiff', plot = VlnPlot9, width = 10, height = 10)

# LUNG

VlnPlot1 <- VlnPlot(linhagens, features = lista_CIFS$V1[1:12], idents = linhagens_sample$value[62:66])
VlnPlot2 <- VlnPlot(linhagens, features = lista_CIFS$V1[13:24], idents = linhagens_sample$value[62:66])
VlnPlot3 <- VlnPlot(linhagens, features = lista_CIFS$V1[25:36], idents = linhagens_sample$value[62:66])
VlnPlot4 <- VlnPlot(linhagens, features = lista_CIFS$V1[37:48], idents = linhagens_sample$value[62:66])
VlnPlot5 <- VlnPlot(linhagens, features = lista_CIFS$V1[49:60], idents = linhagens_sample$value[62:66])
VlnPlot6 <- VlnPlot(linhagens, features = lista_CIFS$V1[61:72], idents = linhagens_sample$value[62:66])
VlnPlot7 <- VlnPlot(linhagens, features = lista_CIFS$V1[73:84], idents = linhagens_sample$value[62:66])
VlnPlot8 <- VlnPlot(linhagens, features = lista_CIFS$V1[85:96], idents = linhagens_sample$value[62:66])
VlnPlot9 <- VlnPlot(linhagens, features = lista_CIFS$V1[97:102], idents = linhagens_sample$value[62:66])

ggsave('Imagens/VLnPLot1.tiff', plot = VlnPlot1, width = 10, height = 10)
ggsave('Imagens/VlnPlot2.tiff', plot = VlnPlot2, width = 10, height = 10)
ggsave('Imagens/VlnPlot3.tiff', plot = VlnPlot3, width = 10, height = 10)
ggsave('Imagens/VlnPlot4.tiff', plot = VlnPlot4, width = 10, height = 10)
ggsave('Imagens/VlnPlot5.tiff', plot = VlnPlot5, width = 10, height = 10)
ggsave('Imagens/VlnPlot6.tiff', plot = VlnPlot6, width = 10, height = 10)
ggsave('Imagens/VlnPlot7.tiff', plot = VlnPlot7, width = 10, height = 10)
ggsave('Imagens/VlnPlot8.tiff', plot = VlnPlot8, width = 10, height = 10)
ggsave('Imagens/VlnPlot9.tiff', plot = VlnPlot9, width = 10, height = 10)

# BONE

VlnPlot1 <- VlnPlot(linhagens, features = lista_CIFS$V1[1:12], idents = linhagens_sample$value[67:69])
VlnPlot2 <- VlnPlot(linhagens, features = lista_CIFS$V1[13:24], idents = linhagens_sample$value[67:69])
VlnPlot3 <- VlnPlot(linhagens, features = lista_CIFS$V1[25:36], idents = linhagens_sample$value[67:69])
VlnPlot4 <- VlnPlot(linhagens, features = lista_CIFS$V1[37:48], idents = linhagens_sample$value[67:69])
VlnPlot5 <- VlnPlot(linhagens, features = lista_CIFS$V1[49:60], idents = linhagens_sample$value[67:69])
VlnPlot6 <- VlnPlot(linhagens, features = lista_CIFS$V1[61:72], idents = linhagens_sample$value[67:69])
VlnPlot7 <- VlnPlot(linhagens, features = lista_CIFS$V1[73:84], idents = linhagens_sample$value[67:69])
VlnPlot8 <- VlnPlot(linhagens, features = lista_CIFS$V1[85:96], idents = linhagens_sample$value[67:69])
VlnPlot9 <- VlnPlot(linhagens, features = lista_CIFS$V1[97:102], idents = linhagens_sample$value[67:69])

ggsave('Imagens/VLnPLot1.tiff', plot = VlnPlot1, width = 10, height = 10)
ggsave('Imagens/VlnPlot2.tiff', plot = VlnPlot2, width = 10, height = 10)
ggsave('Imagens/VlnPlot3.tiff', plot = VlnPlot3, width = 10, height = 10)
ggsave('Imagens/VlnPlot4.tiff', plot = VlnPlot4, width = 10, height = 10)
ggsave('Imagens/VlnPlot5.tiff', plot = VlnPlot5, width = 10, height = 10)
ggsave('Imagens/VlnPlot6.tiff', plot = VlnPlot6, width = 10, height = 10)
ggsave('Imagens/VlnPlot7.tiff', plot = VlnPlot7, width = 10, height = 10)
ggsave('Imagens/VlnPlot8.tiff', plot = VlnPlot8, width = 10, height = 10)
ggsave('Imagens/VlnPlot9.tiff', plot = VlnPlot9, width = 10, height = 10)

# PANCREAS

VlnPlot1 <- VlnPlot(linhagens, features = lista_CIFS$V1[1:12], idents = linhagens_sample$value[70:74])
VlnPlot2 <- VlnPlot(linhagens, features = lista_CIFS$V1[13:24], idents = linhagens_sample$value[70:74])
VlnPlot3 <- VlnPlot(linhagens, features = lista_CIFS$V1[25:36], idents = linhagens_sample$value[70:74])
VlnPlot4 <- VlnPlot(linhagens, features = lista_CIFS$V1[37:48], idents = linhagens_sample$value[70:74])
VlnPlot5 <- VlnPlot(linhagens, features = lista_CIFS$V1[49:60], idents = linhagens_sample$value[70:74])
VlnPlot6 <- VlnPlot(linhagens, features = lista_CIFS$V1[61:72], idents = linhagens_sample$value[70:74])
VlnPlot7 <- VlnPlot(linhagens, features = lista_CIFS$V1[73:84], idents = linhagens_sample$value[70:74])
VlnPlot8 <- VlnPlot(linhagens, features = lista_CIFS$V1[85:96], idents = linhagens_sample$value[70:74])
VlnPlot9 <- VlnPlot(linhagens, features = lista_CIFS$V1[97:102], idents = linhagens_sample$value[70:74])

ggsave('Imagens/VLnPLot1.tiff', plot = VlnPlot1, width = 10, height = 10)
ggsave('Imagens/VlnPlot2.tiff', plot = VlnPlot2, width = 10, height = 10)
ggsave('Imagens/VlnPlot3.tiff', plot = VlnPlot3, width = 10, height = 10)
ggsave('Imagens/VlnPlot4.tiff', plot = VlnPlot4, width = 10, height = 10)
ggsave('Imagens/VlnPlot5.tiff', plot = VlnPlot5, width = 10, height = 10)
ggsave('Imagens/VlnPlot6.tiff', plot = VlnPlot6, width = 10, height = 10)
ggsave('Imagens/VlnPlot7.tiff', plot = VlnPlot7, width = 10, height = 10)
ggsave('Imagens/VlnPlot8.tiff', plot = VlnPlot8, width = 10, height = 10)
ggsave('Imagens/VlnPlot9.tiff', plot = VlnPlot9, width = 10, height = 10)

# OVARY

VlnPlot1 <- VlnPlot(linhagens, features = lista_CIFS$V1[1:12], idents = linhagens_sample$value[75:79])
VlnPlot2 <- VlnPlot(linhagens, features = lista_CIFS$V1[13:24], idents = linhagens_sample$value[75:79])
VlnPlot3 <- VlnPlot(linhagens, features = lista_CIFS$V1[25:36], idents = linhagens_sample$value[75:79])
VlnPlot4 <- VlnPlot(linhagens, features = lista_CIFS$V1[37:48], idents = linhagens_sample$value[75:79])
VlnPlot5 <- VlnPlot(linhagens, features = lista_CIFS$V1[49:60], idents = linhagens_sample$value[75:79])
VlnPlot6 <- VlnPlot(linhagens, features = lista_CIFS$V1[61:72], idents = linhagens_sample$value[75:79])
VlnPlot7 <- VlnPlot(linhagens, features = lista_CIFS$V1[73:84], idents = linhagens_sample$value[75:79])
VlnPlot8 <- VlnPlot(linhagens, features = lista_CIFS$V1[85:96], idents = linhagens_sample$value[75:79])
VlnPlot9 <- VlnPlot(linhagens, features = lista_CIFS$V1[97:102], idents = linhagens_sample$value[75:79])

ggsave('Imagens/VLnPLot1.tiff', plot = VlnPlot1, width = 10, height = 10)
ggsave('Imagens/VlnPlot2.tiff', plot = VlnPlot2, width = 10, height = 10)
ggsave('Imagens/VlnPlot3.tiff', plot = VlnPlot3, width = 10, height = 10)
ggsave('Imagens/VlnPlot4.tiff', plot = VlnPlot4, width = 10, height = 10)
ggsave('Imagens/VlnPlot5.tiff', plot = VlnPlot5, width = 10, height = 10)
ggsave('Imagens/VlnPlot6.tiff', plot = VlnPlot6, width = 10, height = 10)
ggsave('Imagens/VlnPlot7.tiff', plot = VlnPlot7, width = 10, height = 10)
ggsave('Imagens/VlnPlot8.tiff', plot = VlnPlot8, width = 10, height = 10)
ggsave('Imagens/VlnPlot9.tiff', plot = VlnPlot9, width = 10, height = 10)

# OESOPHAGUS 

VlnPlot1 <- VlnPlot(linhagens, features = lista_CIFS$V1[1:12], idents = linhagens_sample$value[80:84])
VlnPlot2 <- VlnPlot(linhagens, features = lista_CIFS$V1[13:24], idents = linhagens_sample$value[80:84])
VlnPlot3 <- VlnPlot(linhagens, features = lista_CIFS$V1[25:36], idents = linhagens_sample$value[80:84])
VlnPlot4 <- VlnPlot(linhagens, features = lista_CIFS$V1[37:48], idents = linhagens_sample$value[80:84])
VlnPlot5 <- VlnPlot(linhagens, features = lista_CIFS$V1[49:60], idents = linhagens_sample$value[80:84])
VlnPlot6 <- VlnPlot(linhagens, features = lista_CIFS$V1[61:72], idents = linhagens_sample$value[80:84])
VlnPlot7 <- VlnPlot(linhagens, features = lista_CIFS$V1[73:84], idents = linhagens_sample$value[80:84])
VlnPlot8 <- VlnPlot(linhagens, features = lista_CIFS$V1[85:96], idents = linhagens_sample$value[80:84])
VlnPlot9 <- VlnPlot(linhagens, features = lista_CIFS$V1[97:102], idents = linhagens_sample$value[80:84])

ggsave('Imagens/VLnPLot1.tiff', plot = VlnPlot1, width = 10, height = 10)
ggsave('Imagens/VlnPlot2.tiff', plot = VlnPlot2, width = 10, height = 10)
ggsave('Imagens/VlnPlot3.tiff', plot = VlnPlot3, width = 10, height = 10)
ggsave('Imagens/VlnPlot4.tiff', plot = VlnPlot4, width = 10, height = 10)
ggsave('Imagens/VlnPlot5.tiff', plot = VlnPlot5, width = 10, height = 10)
ggsave('Imagens/VlnPlot6.tiff', plot = VlnPlot6, width = 10, height = 10)
ggsave('Imagens/VlnPlot7.tiff', plot = VlnPlot7, width = 10, height = 10)
ggsave('Imagens/VlnPlot8.tiff', plot = VlnPlot8, width = 10, height = 10)
ggsave('Imagens/VlnPlot9.tiff', plot = VlnPlot9, width = 10, height = 10)

